# Single source of truth for EMG-O Golden Path test cases — "Block" (ชุดที่ 1 จาก 3:
# Block -> Slab -> FG), rebuilt after ADR-087 "Slab = Lot" (รอบ Slab-Lot, 2026-10-04/05).
#
# Why this doc exists: ADR-087 made Slab a native Odoo Lot and deleted stone.slab,
# so the earlier Golden Path docs (Block->Slab->FG v2, Lot-Mode, Mode 1-5) were
# archived 2026-10-05. The user chose to rebuild the Golden Path as three separate
# stories, Block first, then Slab, then FG. This file is the Block story only:
# set up a stone, buy Blocks, receive them with real sizes, manage them, sell one whole.
#
# Golden Path discipline (see feedback_golden_path_test_case memory): happy path only,
# no field-validation/error cases, every step phrased for a non-technical user.
#
# Data provenance: fresh live run, 2026-10-05, driven through the real Odoo web UI
# (Playwright, headless Chromium) on `eg-tst` (https://eg-tst.mx-erp.com, company
# Empire Granite, user admin), code v2.106 on branch test/emg-erp-ee (merged with
# redesign/slab-lot). Fixtures left in place for the next story (Slab):
#   Material "GP Block Marble" (id 52), PO P00054, receipts EG01/IN/00050 + EG01/IN/00052,
#   Blocks BLK-26-0006 (6.00 m3 after resize), BLK-26-0007 (5.04 m3), BLK-26-0008 (sold),
#   SO S00173, delivery EG01/OUT/00057, invoice INV/2026/00001.
#
# Column model per case: id, scenario, note (optional amber callout), pre, steps (list),
# sample ('-' if nothing to key), expected, prio, shot (screenshot path, clickable).

SHOT = "assets/golden-path-block/"

CATEGORIES = [
  dict(cat_id="B1", title="B1. ตั้งค่าหินชนิดใหม่ (Setup)",
       subtitle="สร้างหิน 1 ชนิดพร้อมสินค้า Block และตั้งราคาขายต่อลูกบาศก์เมตร · 2 test cases",
       cases=[
    dict(id="TC-GP-BLK-01", scenario="สร้างหินชนิดใหม่ด้วย Quick Material Setup พร้อมสินค้า Block",
         pre="เข้าระบบเป็น Empire Granite ได้แล้ว",
         steps=["เปิดแอป Stone Slab &gt; Tools &gt; Quick Material Setup",
                "กรอกชื่อหิน เลือก Category ใส่ความหนาแน่น และราคาขาย/ต้นทุน Slab",
                "เลื่อนลงล่างสุด ติ๊ก \"BLOCK PRODUCT (ขายทั้งก้อนได้)\"",
                "กด \"Create All\""],
         sample="ชื่อ = GP Block Marble<br>Category = Marble<br>Density = 2.7 ตัน/ลบ.ม.<br>Slab Sales Price = 4,500 · Slab Cost = 3,000<br>ติ๊ก Block Product",
         expected="ระบบเปิดหน้า Material ใหม่ พร้อมตาราง LINKED PRODUCTS ที่มีแถว Slab (By Unique Serial Number) และแถว Block (By Lots) — Block ถูกคุมสต็อกเป็น Lot",
         prio="High", shot=SHOT + "gp-blk-01-material-created.png"),
    dict(id="TC-GP-BLK-02", scenario="ตั้งราคาขายของสินค้า Block ต่อลูกบาศก์เมตร (ก่อนรับของ)",
         note="⚠️ ต้องทำก่อนรับของ: หินที่ติ๊ก \"ขายทั้งก้อนได้\" ต้องมีราคาขายต่อลบ.ม. ถ้าลืม ระบบจะไม่ยอมให้ Validate ใบรับของ และแจ้งว่า \"กรุณากรอกราคาขาย/คิว ก่อนบันทึก Block\" (พบจริงในรอบทดสอบนี้ — Quick Setup ยังไม่ถามราคานี้ให้)",
         pre="ทำ TC-GP-BLK-01 เสร็จแล้ว",
         steps=["เปิด Inventory &gt; Products &gt; \"GP Block Marble - Block\"",
                "ช่อง Sales Price (ต่อ m³) กรอกราคา",
                "กด Save"],
         sample="Sales Price = 45,000 บาท ต่อ m³",
         expected="บันทึกราคา 45,000.00 ต่อ m³ ได้ — ราคานี้จะถูกใส่เป็น \"Sales Price / CBM\" ให้ทุก Block ที่รับเข้ามาใหม่อัตโนมัติ",
         prio="High", shot=SHOT + "gp-blk-02-block-price.png"),
  ]),
  dict(cat_id="B2", title="B2. สั่งซื้อ Block (Purchase)",
       subtitle="ซื้อเป็นตัน — ระบบแปลงเป็นลูกบาศก์เมตรให้เอง · 1 test case",
       cases=[
    dict(id="TC-GP-BLK-03", scenario="สร้างใบสั่งซื้อ (PO) Block เป็นตัน แล้ว Confirm",
         note="ช่อง \"จำนวน\" บน PO คือปริมาณโดยประมาณที่สั่ง ไม่ใช่จำนวนก้อน — ขนาดจริงของแต่ละก้อนจะกรอกตอนรับของ ปริมาตรที่ระบบคำนวณปัดทศนิยม 2 ตำแหน่ง (40 ตัน แสดงเป็น 39.99 ตัน = 14.81 ลบ.ม.)",
         pre="ทำ TC-GP-BLK-02 เสร็จแล้ว · มีผู้ขายในระบบ",
         steps=["เปิดแอป Purchase &gt; New",
                "เลือก Vendor แล้วกด \"Add a product\" เลือก \"GP Block Marble - Block\"",
                "กรอก Qty (Ton) และ Price / Ton — ช่อง Quantity (m³) และ Price/m³ คำนวณให้เอง",
                "กด Confirm Order"],
         sample="Vendor = Demo Stone Supplier<br>Qty (Ton) = 40<br>Price / Ton = 6,000",
         expected="PO ขึ้นสถานะ Purchase Order — Quantity 14.81 m³, ราคา 16,200 ต่อ m³ (=6,000×2.7), ยอดก่อน VAT 239,922.00 บาท มีปุ่ม Receive และสมาร์ทปุ่ม Receipt 1 ใบ (ตัวอย่างจริง P00054)",
         prio="High", shot=SHOT + "gp-blk-03-po-line.png"),
  ]),
  dict(cat_id="B3", title="B3. รับ Block เข้าคลัง (Receipt)",
       subtitle="หัวใจของชุดนี้ — 1 แถว = 1 ก้อนจริง กรอกขนาดที่วัดได้จริง · 4 test cases",
       cases=[
    dict(id="TC-GP-BLK-04", scenario="เปิดใบรับของ แล้วกรอกขนาดจริงของ Block 2 ก้อน",
         pre="ทำ TC-GP-BLK-03 เสร็จแล้ว",
         steps=["ที่ PO กดปุ่ม Receive เปิดใบรับของ (ปลายทาง = Stone Available)",
                "ที่แถวสินค้า Block กด \"Details\"",
                "แถวแรกกรอก ยาว × กว้าง × สูง ของก้อนที่ 1",
                "กด \"Add a line\" แล้วกรอกขนาดของก้อนที่ 2",
                "กด Save"],
         sample="ก้อน 1: ยาว 3.0 × กว้าง 1.6 × สูง 1.3 ม.<br>ก้อน 2: ยาว 2.8 × กว้าง 1.5 × สูง 1.2 ม.",
         expected="ระบบคำนวณปริมาตรและน้ำหนักให้ทุกแถว: ก้อน 1 = 6.24 m³ / 16.85 ตัน, ก้อน 2 = 5.04 m³ / 13.61 ตัน, รวม 11.28 m³ — กลับมาที่ใบรับของแถว Block แสดง Quantity 11.28 จากความต้องการ 14.81",
         prio="High", shot=SHOT + "gp-blk-04-details-sizes.png"),
    dict(id="TC-GP-BLK-05", scenario="กด Validate รับของ (รับยังไม่ครบ → สร้าง Backorder)",
         note="รับ 11.28 จากที่สั่ง 14.81 — Odoo ถามว่าจะรับส่วนที่เหลือทีหลังไหม เลือก \"Create Backorder\" เพื่อให้เหลือใบรับสำหรับก้อนที่ยังไม่มาถึง",
         pre="ทำ TC-GP-BLK-04 เสร็จแล้ว",
         steps=["กดปุ่ม Validate บนใบรับของ",
                "เมื่อมีหน้าต่าง \"Create Backorder?\" กด \"Create Backorder\""],
         sample="-",
         expected="ใบรับของขึ้น Done · ระบบแจ้งเตือนสีเขียวว่า \"สร้าง Block สำเร็จ BLK-26-0006 รับสต็อกเข้าคลังแล้ว 6.240 m3\" และ BLK-26-0007 (5.040 m3) · ระบบสร้างใบรับใหม่ (Backorder) สำหรับส่วนที่เหลือให้อัตโนมัติ",
         prio="High", shot=SHOT + "gp-blk-05-validate-backorder.png"),
    dict(id="TC-GP-BLK-06", scenario="ตรวจว่าได้ Block 2 ก้อนในระบบ และ PO ขึ้นยอดรับแล้ว",
         pre="ทำ TC-GP-BLK-05 เสร็จแล้ว",
         steps=["เปิดแอป Stone Slab &gt; Blocks",
                "ดูการ์ด Block ที่เพิ่งเกิด",
                "กลับไปที่ PO ดูคอลัมน์ Received"],
         sample="-",
         expected="มี Block ใหม่ 2 ใบ: BLK-26-0006 (เหลือ 6.24 CBM / 16.85 ตัน) และ BLK-26-0007 (เหลือ 5.04 CBM / 13.61 ตัน) ชื่อหินและผู้ขายถูกต้อง · PO แสดง Received = 11.28 จาก 14.81",
         prio="High", shot=SHOT + "gp-blk-06-blocks-list.png"),
    dict(id="TC-GP-BLK-07", scenario="รับ Block ก้อนที่ 3 จากใบ Backorder จนครบ",
         pre="ทำ TC-GP-BLK-05 เสร็จแล้ว (มีใบ Backorder)",
         steps=["เปิดใบรับของที่เป็น Backorder (จากสมาร์ทปุ่ม Receipt บน PO)",
                "กด Details กรอกขนาดก้อนที่ 3 แล้ว Save",
                "กด Validate"],
         sample="ก้อน 3: ยาว 2.0 × กว้าง 1.47 × สูง 1.2 ม.",
         expected="ได้ BLK-26-0008 (3.528 m³ / 9.53 ตัน) ใบรับขึ้น Done และไม่ถามเรื่อง Backorder อีก · PO แสดง Received = 14.81 ครบ (ตัวอย่างจริง: Backorder EG01/IN/00052)",
         prio="Medium", shot=SHOT + "gp-blk-07-backorder-received.png"),
  ]),
  dict(cat_id="B4", title="B4. ดูและจัดการ Block",
       subtitle="ดูข้อมูลของ Block และแก้ขนาดเมื่อวัดผิด · 2 test cases",
       cases=[
    dict(id="TC-GP-BLK-08", scenario="เปิดหน้า Block ดูขนาด ปริมาตร น้ำหนัก ต้นทุน และที่มา",
         pre="ทำ TC-GP-BLK-05 เสร็จแล้ว",
         steps=["เปิด Stone Slab &gt; Blocks",
                "คลิกการ์ด BLK-26-0006"],
         sample="-",
         expected="เห็น Material = GP Block Marble, ผู้ขาย, ใบ PO ที่มา (P00054), ขนาด 3.00 × 1.60 × 1.30 ม., Total CBM 6.24, น้ำหนัก 16.85 ตัน, ราคาขาย 45,000/CBM, ต้นทุน PO 16,200/CBM, Lot BLK-26-0006-BLK, คงเหลือ 6.24, ประมาณการผลผลิตแผ่น 312 ตร.ม. (65 แผ่น) · ปุ่ม \"แก้ขนาด\" อยู่ด้านซ้ายบน",
         prio="Medium", shot=SHOT + "gp-blk-08-block-form.png"),
    dict(id="TC-GP-BLK-09", scenario="แก้ขนาด Block ที่วัดผิด (ผู้จัดการคลัง) พร้อมเหตุผล",
         note="ใช้ได้เฉพาะ Inventory Manager และต้องใส่เหตุผลทุกครั้ง — ระบบปรับสต็อกส่วนต่างด้วยการปรับสต็อกมาตรฐานของ Odoo และเก็บประวัติให้",
         pre="ทำ TC-GP-BLK-08 เสร็จแล้ว · Block นี้ยังไม่ถูกตัด",
         steps=["เปิด Block BLK-26-0006 กดปุ่ม \"แก้ขนาด\"",
                "ในช่อง \"สูงใหม่\" ใส่ความสูงที่วัดซ้ำได้",
                "เขียนเหตุผลที่แก้",
                "กดปุ่ม \"แก้ขนาด\" ในหน้าต่าง",
                "เปิดแท็บ \"ประวัติแก้ขนาด\""],
         sample="สูงใหม่ = 1.25 ม. (เดิม 1.30)<br>เหตุผล = วัดซ้ำหน้างาน ความสูงจริง 1.25 ม. (กรอกตอนรับของผิด)",
         expected="Total CBM เปลี่ยน 6.24 → 6.00 · แท็บประวัติมี 1 แถว: เวลา, ผู้แก้, ขนาดเดิม/ใหม่, CBM เดิม/ใหม่, ปรับสต็อก −0.24, พร้อมเหตุผล",
         prio="Medium", shot=SHOT + "gp-blk-09-resize-history.png"),
  ]),
  dict(cat_id="B5", title="B5. ขาย Block ทั้งก้อน (Sell Whole Block)",
       subtitle="ขาย → ส่งของ → ออกใบแจ้งหนี้ และตรวจต้นทุนขาย · 3 test cases",
       cases=[
    dict(id="TC-GP-BLK-10", scenario="สร้างใบสั่งขาย เลือก \"Sell Whole Block\" แล้ว Confirm",
         pre="มี Block ที่ยังไม่ถูกตัด (เช่น BLK-26-0008) · มีลูกค้าในระบบ",
         steps=["เปิดแอป Sales &gt; New เลือกลูกค้า",
                "Add a product เลือก \"GP Block Marble - Block\" แล้วกด Save",
                "ที่บรรทัดสินค้ากดลิงก์ \"Sell Whole Block\"",
                "ในหน้าต่าง Select Block เลือกก้อนที่ต้องการ แล้วกด \"Confirm Selection\"",
                "กด Confirm"],
         sample="ลูกค้า = Demo Hotel Customer<br>Block = BLK-26-0008",
         expected="จำนวนและราคาขึ้นให้เองจากปริมาตรจริง: 3.53 m³ × 45,000 = 158,850.00 บาท (+ VAT 11,119.50 = 169,969.50) · SO เป็น Sales Order และมีสมาร์ทปุ่ม Delivery 1 ใบ (ตัวอย่างจริง S00173)",
         prio="High", shot=SHOT + "gp-blk-10-so-line.png"),
    dict(id="TC-GP-BLK-11", scenario="ส่งของ (Delivery) Block ให้ลูกค้า",
         pre="ทำ TC-GP-BLK-10 เสร็จแล้ว",
         steps=["ที่ SO กดสมาร์ทปุ่ม Delivery",
                "ตรวจว่า Source Location = Stone Available แล้วกด Validate"],
         sample="-",
         expected="ใบส่งของขึ้น Done ปริมาณ 3.53 m³ / 9.53 ตัน ตัดสต็อกออกจาก Stone Available (ตัวอย่างจริง EG01/OUT/00057)",
         prio="High", shot=SHOT + "gp-blk-11-delivery-done.png"),
    dict(id="TC-GP-BLK-12", scenario="ออกใบแจ้งหนี้ และตรวจรายการบัญชี (รายได้ + ต้นทุนขาย)",
         note="ข้อสังเกตสำหรับฝ่ายบัญชี: ในรอบทดสอบนี้ สต็อก Block ถูกตัดจากบัญชี 113120 \"Inventory - Stone Slabs (Ready-Made)\" ซึ่งชื่อเป็นของ Slab — ยอดตัวเลขถูกต้อง แต่ควรให้ฝ่ายบัญชีดูว่าต้องการแยกบัญชีสต็อก Block หรือไม่ (ยังไม่ได้ตัดสินใจ)",
         pre="ทำ TC-GP-BLK-11 เสร็จแล้ว",
         steps=["ที่ SO กด Create Invoice &gt; เลือก Regular invoice &gt; Create Draft",
                "ที่ใบแจ้งหนี้ กด Confirm",
                "เปิดแท็บ Journal Items"],
         sample="-",
         expected="ใบแจ้งหนี้ขึ้น Posted (INV/2026/00001) · รายการบัญชีสมดุลที่ 227,155.50: รายได้ 411100 = 158,850.00 · ต้นทุนขาย 511110 = 57,186.00 (=3.53 × 16,200 ตรงกับต้นทุน PO) · ตัดสต็อก 113120 = 57,186.00 · VAT 213200 = 11,119.50 · ลูกหนี้ 112100 = 169,969.50",
         prio="High", shot=SHOT + "gp-blk-12-invoice-journal.png"),
  ]),
]
