# Single source of truth for EMG-O QA test cases (Product Master & Sales).
# Regenerated 2026-08-26 to (1) strip backend field/method names a UI tester
# can't see, (2) add concrete "sample data to key in" per case, (3) correct
# several cases that described functionality not present in the current code
# (see CORRECTIONS below). Feed this into build_html.py and build_xlsx.py.
#
# CORRECTIONS made vs the previous version (confirmed against
# stone_slab_inventory + boq_estimation source, 2026-08-26):
#   - A1: dropped old TC-A1-06 (External UID / slabware_uid) - field is not
#     placed on any view, only reachable via the inbound sync API. Not
#     testable through the UI at all.
#   - A5: Finish is a field on the Block form (applies to both Block-tracked
#     and Lot-mode materials), not something chosen inside the Cut Order
#     wizard - rewrote steps to match.
#   - A7: old TC-A7-01/03 tested a "labor_cost_sqmt" field and a
#     "_compute_labor_cost()" method that do not exist anywhere in the code.
#     Slab cost is only ever flat-cost or cost_sqmt x area; there is no
#     material-level labor-per-sqmt term. Dropped both, kept only the real
#     MRP-workcenter-based labor costing case.
#   - B3: old TC-B3-01/02 described a "_check_block_at_production()" guard
#     and a manual Internal Transfer step that do not exist. The real
#     behaviour is automatic CBM deduction on save, guarded only by a
#     "not enough Block stock remaining" check - rewrote both cases around
#     that real guard instead.
#   - B4: old TC-B4-03/04/06/07/09 described a per-BOQ-line "is_milestone"
#     checkbox and a "regenerate milestones" button - that mechanism belongs
#     to the unrelated ptj_project module, not EMG-O's BOQ-to-Project flow.
#     The real flow always creates a fixed 30/40/30 milestone template and
#     one Task per non-section order line with no zone/schedule grouping.
#     Rewrote 03/04/06/07 to match; dropped 09 (no real equivalent).
#
# Column model per test case:
#   id, scenario, note (optional amber callout), pre, steps (list),
#   sample (str, the "key this in" data - '-' if the case has nothing to key),
#   expected, prio (High/Medium/Low)

CATEGORIES = [
  dict(cat_id="A1", title="A1. สร้าง Material พื้นฐาน",
       subtitle="Required fields + unique constraints · 5 test cases",
       cases=[
    dict(id="TC-A1-01", scenario="สร้าง Material ครบทุกฟิลด์บังคับ",
         pre="ผู้ใช้มีสิทธิ์ EMG-O Internal Manager",
         steps=["เปิดเมนู Stone Material &gt; New", "กรอกฟิลด์บังคับให้ครบ", "กด Save"],
         sample="Name = \"Test Marble 01\"<br>Category = \"Marble\"<br>Pricing Mode = \"Serial (per-slab)\"<br>Costing Basis = \"Area (Sq.Mt.)\"<br>Slab Product = เลือกสินค้าที่มีอยู่ เช่น \"Carrara White Slab\"",
         expected="บันทึกสำเร็จ ไม่มี error", prio="High"),
    dict(id="TC-A1-02", scenario="สร้าง Material โดยไม่กรอก Name", pre="-",
         steps=["เปิด New", "เว้นช่อง Name ว่าง", "กรอกฟิลด์อื่นครบตาม TC-A1-01", "กด Save"],
         sample="Name = (เว้นว่าง) — ฟิลด์อื่นเหมือน TC-A1-01",
         expected="ระบบฟ้อง required field ที่ช่อง Name บันทึกไม่ผ่าน", prio="Medium"),
    dict(id="TC-A1-03", scenario="สร้าง Material โดยไม่เลือก Category", pre="-",
         steps=["เปิด New", "เว้น Category ว่าง", "กรอกฟิลด์อื่นครบ", "กด Save"],
         sample="Category = (เว้นว่าง) — ฟิลด์อื่นเหมือน TC-A1-01",
         expected="ระบบฟ้อง required field ที่ช่อง Category บันทึกไม่ผ่าน", prio="Medium"),
    dict(id="TC-A1-04", scenario="สร้าง Material โดยไม่ผูก Slab Product", pre="-",
         steps=["เปิด New", "เว้นช่อง Slab Product ว่าง", "กรอกฟิลด์อื่นครบ", "กด Save"],
         sample="Slab Product = (เว้นว่าง) — ฟิลด์อื่นเหมือน TC-A1-01",
         expected="ระบบฟ้อง required field ที่ช่อง Slab Product (ต่างจาก Block Product ซึ่งเว้นว่างได้)", prio="High"),
    dict(id="TC-A1-05", scenario="สร้าง Material ชื่อซ้ำกับที่มีอยู่แล้ว",
         pre="มี Material ชื่อ \"Carrara White\" อยู่แล้ว",
         steps=["สร้าง Material ใหม่", "ตั้งชื่อ \"Carrara White\" ซ้ำเป๊ะกับตัวที่มีอยู่", "กด Save"],
         sample="Name = \"Carrara White\" (พิมพ์ซ้ำตัวที่มีอยู่เป๊ะๆ)",
         expected="ระบบฟ้องว่าชื่อซ้ำ บันทึกไม่ผ่าน", prio="Medium"),
  ]),
  dict(cat_id="A2", title="A2. Pricing Mode (Serial vs Lot)",
       subtitle="ADR-020 Mode 2 — ล็อกเมื่อมี Block อยู่แล้ว · 5 test cases",
       cases=[
    dict(id="TC-A2-01", scenario="สร้าง Material ใหม่ ไม่ระบุ Pricing Mode", pre="-",
         steps=["เปิด New", "ไม่แตะช่อง Pricing Mode", "กรอกฟิลด์บังคับอื่นครบ", "กด Save"],
         sample="ไม่ต้องเลือก Pricing Mode เลย ปล่อยเป็นค่าเริ่มต้น",
         expected="Pricing Mode ขึ้นเป็น \"Serial (per-slab)\" โดยอัตโนมัติ", prio="Medium"),
    dict(id="TC-A2-02", scenario="สร้าง Material เลือก Pricing Mode = Lot", pre="-",
         steps=["เปิด New", "เลือก Pricing Mode = \"Lot (aggregate, cheap stone)\"", "เลือก Slab Product ที่ Tracking (แท็บ Inventory ของสินค้า) ยังไม่ใช่ \"By Lots\"", "กด Save"],
         sample="Pricing Mode = \"Lot (aggregate, cheap stone)\"<br>Slab Product = สินค้าที่ Tracking ยังเป็น \"No Tracking\" หรือ \"By Unique Serial Number\"",
         expected="บันทึกสำเร็จ และเมื่อเปิดสินค้านั้นดูอีกครั้ง ฟิลด์ Tracking ถูกเปลี่ยนเป็น \"By Lots\" ให้อัตโนมัติ", prio="High"),
    dict(id="TC-A2-03", scenario="Material ยังไม่มี Block เลย — เปลี่ยน Pricing Mode",
         pre="Material ใหม่ ยังไม่มี Block/Lot ผูกอยู่เลย",
         steps=["เปิด Material ที่ Pricing Mode = Serial", "เปลี่ยนเป็น Lot", "กด Save"],
         sample="เปลี่ยน Pricing Mode จาก \"Serial (per-slab)\" เป็น \"Lot (aggregate, cheap stone)\"",
         expected="เปลี่ยนได้ปกติ ไม่มี error", prio="Medium"),
    dict(id="TC-A2-04", scenario="Material มี Block อยู่แล้ว — พยายามเปลี่ยน Pricing Mode",
         note="หมายเหตุ: กันสถานะสต็อกปนกัน",
         pre="Material มี Block/Lot อย่างน้อย 1 รายการอยู่แล้ว (เช่น BDL-00002)",
         steps=["เปิด Material นั้น", "พยายามเปลี่ยน Pricing Mode จาก Serial เป็น Lot (หรือกลับกัน)", "กด Save"],
         sample="สลับค่า Pricing Mode ไปอีกฝั่งหนึ่ง",
         expected="ขึ้น error ภาษาไทยแจ้งว่า Pricing Mode ถูกล็อกแล้ว บันทึกไม่ผ่าน", prio="High"),
    dict(id="TC-A2-05", scenario="เปลี่ยน Slab Product ของ Material ที่เป็น Lot mode อยู่แล้ว",
         pre="Material ตั้ง Pricing Mode = Lot อยู่แล้ว",
         steps=["เปิด Material", "เปลี่ยน Slab Product เป็นสินค้าอื่นที่ Tracking ยังไม่ใช่ \"By Lots\"", "กด Save"],
         sample="Slab Product = สินค้าใหม่ที่ Tracking เป็น \"No Tracking\"",
         expected="เปิดสินค้าใหม่นั้นดู — Tracking ถูกบังคับเป็น \"By Lots\" ให้อัตโนมัติเช่นกัน", prio="Medium"),
  ]),
  dict(cat_id="A3", title="A3. Costing Basis (Area vs Count)",
       subtitle="ADR-030 — สูตรคำนวณต้นทุน/ราคาแผ่น · 4 test cases",
       cases=[
    dict(id="TC-A3-01", scenario="สร้าง Material ใหม่ ไม่ระบุ Costing Basis", pre="-",
         steps=["เปิด New", "ไม่แตะ Costing Basis", "กด Save"],
         sample="ไม่ต้องเลือก Costing Basis เลย",
         expected="Costing Basis ขึ้นเป็น \"Area (Sq.Mt.)\" โดยอัตโนมัติ", prio="Low"),
    dict(id="TC-A3-02", scenario="ตั้ง Costing Basis = Count พร้อม Flat Cost/Price",
         pre="Material ใหม่ตั้ง Costing Basis = \"Count (flat per piece)\"",
         steps=["กรอก Flat Cost / Piece และ Flat Sale Price / Piece", "เปิด Block ของ Material นี้ &gt; แท็บ Slabs &gt; เพิ่ม 1 แถว", "ตรวจ Cost ของแผ่นที่ได้ (คอลัมน์ Cost หรือเปิดแผ่นดู)"],
         sample="Flat Cost / Piece = 1,500<br>Flat Sale Price / Piece = 2,500<br>Slab L / Slab H = ใส่เท่าไหร่ก็ได้ (ไม่มีผลกับราคาโหมดนี้)",
         expected="Cost และราคาขายของแผ่นเท่ากับ 1,500 / 2,500 เป๊ะ ไม่ถูกคำนวณจากขนาดแผ่น", prio="High"),
    dict(id="TC-A3-03", scenario="ตั้ง Costing Basis = Length (ยังไม่รองรับสูตรจริง)",
         note="หมายเหตุ: รอ confirm สูตรจริงกับทีมประเมินราคา",
         pre="Material ใหม่ตั้ง Costing Basis = \"Length\"",
         steps=["เปิด Block ของ Material นี้ &gt; แท็บ Slabs &gt; เพิ่ม 1 แถว ระบุ Slab L / Slab H", "ตรวจ Cost ของแผ่นที่ได้"],
         sample="Slab L (M) = 2.0<br>Slab H (M) = 1.5<br>Cost / Sq.Mt. ของ Block = 1,000",
         expected="ระบบคำนวณ Cost แบบพื้นที่เหมือน Area mode (2.0 × 1.5 × 1,000 = 3,000) ไม่ error แม้ยังไม่มีสูตร Length จริง", prio="Medium"),
    dict(id="TC-A3-04", scenario="Costing Basis = Area (ค่าเริ่มต้น) — regression",
         pre="Material ตั้ง Costing Basis = \"Area (Sq.Mt.)\" (ค่าเริ่มต้น)",
         steps=["เปิด Block &gt; แท็บ Slabs &gt; เพิ่ม 1 แถว ระบุ Slab L / Slab H", "ตรวจ Cost ของแผ่นที่ได้"],
         sample="Slab L (M) = 2.0<br>Slab H (M) = 1.5<br>Cost / Sq.Mt. ของ Block = 1,000",
         expected="Cost = 3,000 (2.0 × 1.5 × 1,000) ตามพฤติกรรมเดิมทุกประการ", prio="High"),
  ]),
  dict(cat_id="A4", title="A4. Product Linkage &amp; Control Policy Self-Heal",
       subtitle="Slab Product / Block Product ถูกบังคับ Control Policy = \"Ordered quantities\" เสมอ · 4 test cases",
       cases=[
    dict(id="TC-A4-01", scenario="ผูก Slab Product ที่ Control Policy เดิมเป็น \"Received quantities\"",
         note="หมายเหตุ: กันบิลได้ยอด 0 เพราะไม่เคยยืนยันใบรับสินค้าจริง",
         pre="มีสินค้า (product) ที่ตั้ง Control Policy (แท็บ Purchase ของสินค้า) = \"Received quantities\" อยู่ก่อน",
         steps=["สร้าง Material ใหม่ ผูก Slab Product เป็นสินค้านั้น", "กด Save", "เปิดสินค้านั้นดูแท็บ Purchase อีกครั้ง"],
         sample="Slab Product = สินค้าที่ Control Policy เดิม = \"Received quantities\"",
         expected="Control Policy ของสินค้าถูกเปลี่ยนเป็น \"Ordered quantities\" ให้อัตโนมัติ", prio="High"),
    dict(id="TC-A4-02", scenario="ผูก Block Product ทีหลัง",
         pre="Material มีอยู่แล้ว ยังไม่ได้ผูก Block Product",
         steps=["เปิด Material", "ผูก Block Product เป็นสินค้าที่ Control Policy = \"Received quantities\"", "กด Save"],
         sample="Block Product = สินค้าที่ Control Policy เดิม = \"Received quantities\"",
         expected="Control Policy ของ Block Product ถูกเปลี่ยนเป็น \"Ordered quantities\" เช่นกัน", prio="Medium"),
    dict(id="TC-A4-03", scenario="แก้ Slab Product ของ Material ที่มีอยู่ไปเป็นสินค้าอื่น",
         pre="Material มี Slab Product เดิมอยู่แล้ว",
         steps=["เปิด Material", "เปลี่ยน Slab Product เป็นสินค้าใหม่ (Control Policy = \"Received quantities\")", "กด Save"],
         sample="Slab Product = สินค้าใหม่ที่ Control Policy เดิม = \"Received quantities\"",
         expected="Control Policy ของสินค้าใหม่ถูกเปลี่ยนเป็น \"Ordered quantities\"", prio="Medium"),
    dict(id="TC-A4-04", scenario="ไม่ผูก Block Product เลย (ปล่อยว่าง)", pre="-",
         steps=["สร้าง Material ใหม่ กรอกฟิลด์บังคับครบ", "เว้น Block Product ว่างไว้", "กด Save"],
         sample="Block Product = (เว้นว่าง)",
         expected="บันทึกสำเร็จปกติ (Block Product ไม่ใช่ฟิลด์บังคับ)", prio="Low"),
  ]),
  dict(cat_id="A5", title="A5. Finish / Variant Resolution",
       subtitle="ADR-018 — Finish ของ Block เป็นตัวกำหนด Variant ที่ใช้ตัด/ผลิต · 4 test cases",
       cases=[
    dict(id="TC-A5-01", scenario="Material ที่ Slab Product ยังไม่มี Finish ให้เลือกเลย",
         pre="Slab Product ของ Material นี้มีตัวเลือกเดียว ไม่มี Finish ให้เลือกหลายแบบ",
         steps=["เปิด Block ของ Material นี้", "ลองตั้งค่า Finish เป็นค่าใดก็ได้ (หรือปล่อยว่าง)", "ไปแท็บ Slabs เพิ่ม 1 แถว หรือกด \"Create Cut Order\""],
         sample="Finish = เลือกอะไรก็ได้ เช่น \"Polished\" หรือปล่อยว่าง",
         expected="ทำงานได้ปกติเหมือนกันทุกครั้ง ไม่ error ไม่ว่าจะตั้งค่า Finish เป็นอะไร", prio="Medium"),
    dict(id="TC-A5-02", scenario="Material ที่ Slab Product มี Finish ให้เลือกหลายแบบ",
         note="หมายเหตุ: เคยพบบั๊กผลิตผิด Finish มาก่อน (แก้แล้ว 2026-07-19)",
         pre="Slab Product ของ Material นี้มีตัวเลือก Finish หลายแบบ (เช่น Polished/Honed) พร้อมใช้งานแล้ว",
         steps=["เปิด Block ของ Material นี้", "ตั้งค่า Finish = \"Polished\"", "ไปแท็บ Slabs เพิ่ม 1 แถว หรือกด \"Create Cut Order\" แล้วยืนยัน MO"],
         sample="Finish = \"Polished\"",
         expected="แผ่น/สินค้าที่ได้ตรงกับ Finish = Polished จริง ไม่ใช่ตัวเลือกเริ่มต้นแบบไม่ระบุ Finish", prio="High"),
    dict(id="TC-A5-03", scenario="ปล่อย Finish ว่างไว้ ทั้งที่มีให้เลือกหลายแบบ",
         pre="Slab Product ของ Material นี้มีตัวเลือก Finish หลายแบบ",
         steps=["เปิด Block ของ Material นี้", "ปล่อยช่อง Finish ว่างไว้ (ไม่เลือก)", "ไปแท็บ Slabs ลองเพิ่มแถวแรก"],
         sample="Finish = (เว้นว่าง)",
         expected="ระบบฟ้อง error ภาษาไทยให้ตั้งค่า Finish ก่อนเพิ่มแผ่น บันทึกไม่ผ่าน", prio="Medium"),
    dict(id="TC-A5-04", scenario="Regression: เพิ่ม Finish แบบที่ 2 แล้ว Select Slabs/Cut-to-Order ต้องไม่หาย",
         note="หมายเหตุ: พบและแก้แล้ว 2026-07-19 — regression case",
         pre="Material ที่เพิ่งเพิ่มตัวเลือก Finish แบบที่ 2 ให้กับ Slab Product (Odoo จะปิดการใช้งาน variant เดิมอัตโนมัติ)",
         steps=["เปิด SO เลือก Material นี้", "กด \"Select Slabs\" หรือ \"Cut to Order\""],
         sample="-",
         expected="ปุ่ม/ตัวเลือกยังใช้งานได้ปกติ ไม่หายไปเงียบๆ", prio="High"),
  ]),
  dict(cat_id="A6", title="A6. BOM ถูกสร้างอัตโนมัติ (Cut-to-Order / FG Production)",
       subtitle="BOM/Workcenter/Operation Type ถูกสร้างให้อัตโนมัติแยกตาม Company · 5 test cases",
       cases=[
    dict(id="TC-A6-01", scenario="Cut-to-Order ครั้งแรกของ Material+Company คู่ใหม่",
         pre="Material นี้ยังไม่เคยสร้าง Cut Order สำหรับ Company นี้เลย",
         steps=["เปิด Block ของ Material นี้ กด \"Create Cut Order\" (หรือกด \"Cut to Order\" จาก SO line)", "กรอกฟิลด์ในหน้าต่าง \"Create Cut Order\"", "ตรวจ Manufacturing &gt; Work Centers และ Bill of Materials"],
         sample="Target L (M) = 2.0<br>Target H (M) = 1.2<br>Cut From Block = เลือก Block ที่มีอยู่ (เช่น BLK-26-0002)",
         expected="ระบบสร้าง Work Center \"Stone Cutting\", Operation Type \"Stone Cutting\" และ Bill of Materials ให้เองครบ ไม่ต้องตั้งค่าเอง", prio="High"),
    dict(id="TC-A6-02", scenario="Cut-to-Order ครั้งที่สองของ Material+Company เดิม",
         pre="ทำ TC-A6-01 ไปแล้ว มี BOM อยู่แล้ว",
         steps=["สร้าง Cut Order อีกครั้งของ Material/Company เดิม", "ตรวจจำนวน Bill of Materials ของสินค้านี้"],
         sample="ใช้ Material/Company เดิมกับ TC-A6-01",
         expected="ใช้ BOM ใบเดิมซ้ำ ไม่มี BOM ใบใหม่เกิดขึ้นซ้อน", prio="Medium"),
    dict(id="TC-A6-03", scenario="Material เดียวกัน Cut-to-Order จาก 2 บริษัท (Empire Granite, Empire Stone)",
         note="หมายเหตุ: เคยพบบั๊กสลับบริษัทผิดมาก่อน (แก้แล้ว 2026-07-22)",
         pre="Material นี้ถูกใช้ทั้ง 2 บริษัท",
         steps=["สร้าง Cut Order จากคลังของ Empire Granite", "สร้าง Cut Order จากคลังของ Empire Stone (Material เดียวกัน)", "ตรวจ Bill of Materials ที่ได้ทั้งสองใบ"],
         sample="Material เดียวกัน ทำ 2 รอบ คนละ Company",
         expected="ได้ BOM แยกกันคนละใบต่อบริษัท ไม่ใช้ปนกัน (แต่ละใบชี้ Work Center/Operation Type ของบริษัทตัวเอง)", prio="High"),
    dict(id="TC-A6-04", scenario="ผู้ใช้สิทธิ์ EMG-O Factory Admin ธรรมดา กด Cut to Order ครั้งแรก",
         pre="ผู้ใช้ไม่มีสิทธิ์ Manufacturing Administrator (มีแค่สิทธิ์ EMG-O ปกติ)",
         steps=["Login ด้วยผู้ใช้สิทธิ์จำกัดนี้", "สร้าง Cut Order ครั้งแรกของ Material/Company ที่ยังไม่เคยมี BOM"],
         sample="-",
         expected="สร้างสำเร็จ ไม่ขึ้น Access Error ระหว่างขั้นตอนที่ระบบสร้าง BOM/Work Center/Operation Type ให้อัตโนมัติ", prio="High"),
    dict(id="TC-A6-05", scenario="FG Production ครั้งแรกของ FG variant+Company คู่ใหม่",
         pre="Product Category ของสินค้า FG นี้ตั้งรายการขั้นตอนงาน (เช่น Polishing, Edge) ไว้แล้ว",
         steps=["สั่งผลิตสินค้า FG นี้ครั้งแรกจากบริษัทหนึ่ง (กด \"Produce FG\" จาก SO line)", "ตรวจ Operation Type \"Stone FG Production\" และ BOM ที่ได้"],
         sample="เลือก Slab to Consume ที่มีอยู่จริงในสต็อก",
         expected="ระบบสร้าง Operation Type และ BOM ให้อัตโนมัติ โดย BOM มี Slab ต้นทางเป็นวัตถุดิบ (จำนวน 1.0) และขั้นตอนงานเรียงตามลำดับที่ตั้งไว้ในหมวดสินค้าครบทุกขั้น", prio="Medium"),
  ]),
  dict(cat_id="A7", title="A7. Labor Cost / Sq.Mt.",
       subtitle="ค่าแรงตัดถูกคิดรวมเข้า Total Cost ของแผ่นอัตโนมัติ ไม่ว่าจะตัดด้วยมือหรือผ่าน MO · 3 test cases",
       cases=[
    dict(id="TC-A7-01", scenario="ตัดแผ่นด้วยมือ (\"Add a line\" บนแท็บ Slabs, ไม่ผ่าน Cut Order/MO) บน Material ที่ตั้งค่าแรงต่อตร.ม. ไว้",
         pre="Material ตั้งค่า \"Cutting Labor Cost / Sq.Mt.\" มากกว่า 0 (Costing Basis เป็น \"Area (Sq.Mt.)\")",
         steps=["เปิด Block ของ Material นี้ &gt; แท็บ Slabs &gt; กด \"Add a line\" กรอก Slab L / Slab H แล้วบันทึก", "เปิดเมนู Slabs (เมนูบนสุด) หาแผ่นที่เพิ่งเพิ่มไป เปิดดู"],
         sample="Cutting Labor Cost / Sq.Mt. = 200<br>Slab L (M) = 2.0<br>Slab H (M) = 1.5",
         expected="Total Cost ของแผ่น = ต้นทุนวัสดุ (Cost) บวกค่าแรง (200 × 3.0 ตร.ม. = 600) เข้าไปด้วย", prio="Medium"),
    dict(id="TC-A7-02", scenario="ตัดแผ่นผ่าน Cut-to-Order (มี Manufacturing Order จริง)",
         pre="Material ตั้ง \"Cutting Labor Cost / Sq.Mt.\" มากกว่า 0 เช่นกัน และ Block อยู่ที่ Stone Production แล้ว",
         steps=["สร้าง Cut Order แล้ว Confirm Manufacturing Order ให้ตัดแผ่นจริง", "เปิดเมนู Slabs หาแผ่นที่ได้ เปิดดู Total Cost และรายการ Analytic ของค่าแรงบน Sale Order"],
         sample="Target L (M) = 2.0<br>Target H (M) = 1.2",
         expected="ค่าแรงในแผ่นนี้มาจาก Cost/hr ของ Work Center × เวลาที่ใช้จริงบน Work Order เท่านั้น ไม่บวก \"Cutting Labor Cost / Sq.Mt.\" ซ้ำเข้าไปอีก (ไม่ double-count)", prio="High"),
    dict(id="TC-A7-03", scenario="Material ที่ Costing Basis = Count",
         pre="Material ตั้งค่า \"Cutting Labor Cost / Sq.Mt.\" ไว้ตั้งแต่ตอน Costing Basis ยังเป็น Area (ช่องนี้จะซ่อนไปเมื่อสลับเป็น Count แต่ค่าที่ตั้งไว้เดิมยังมีผล) แล้วจึงเปลี่ยน Costing Basis เป็น \"Count (flat per piece)\"",
         steps=["เปิด Block ของ Material นี้ &gt; แท็บ Slabs &gt; กด \"Add a line\"", "เปิดเมนู Slabs หาแผ่นที่ได้ เปิดดู Total Cost"],
         sample="-",
         expected="ค่าแรงต่อตร.ม. ไม่ถูกนำมาบวก (โหมดนี้ไม่มีฐาน Sq.Mt. ให้คูณ) Total Cost อิงจาก Flat Cost/Piece เท่านั้น", prio="Low"),
  ]),
  dict(cat_id="B1", title="B1. Mode 1 — Block Direct Sale",
       subtitle="ADR-019 — ขายทั้งก้อนหินตาม CBM · 4 test cases",
       cases=[
    dict(id="TC-B1-01", scenario="เลือก Block ผ่าน \"Sell Whole Block\" ใน SO",
         pre="มี Block สถานะ Available อยู่",
         steps=["เปิด SO เพิ่มบรรทัด กด \"Sell Whole Block\"", "หน้าต่าง \"Select Block\" เลือก Block หนึ่งก้อน", "กด \"Confirm Selection\""],
         sample="เลือก Block ที่สถานะ Available เช่น \"BLK-00007\"",
         expected="บรรทัด SO ผูก Block ถูกต้อง สินค้าในบรรทัดเปลี่ยนเป็น Block Product ของ Material นั้น", prio="High"),
    dict(id="TC-B1-02", scenario="Confirm SO Mode 1 ภายในบริษัทเดียวกัน",
         pre="Block และ SO อยู่บริษัทเดียวกัน",
         steps=["Confirm SO", "ตรวจ Delivery Order ที่เกิดขึ้น"],
         sample="-",
         expected="ได้ Delivery ปกติ ไม่มี SO/PO ภายในบริษัทเกิดขึ้นเพิ่ม", prio="High"),
    dict(id="TC-B1-03", scenario="พยายามเลือก Block ที่ถูกขายไปแล้วโดย SO อื่น",
         pre="Block ถูกผูกกับ SO อื่นไปแล้ว",
         steps=["เปิดหน้าต่าง \"Select Block\" บน SO ใหม่"],
         sample="-",
         expected="Block ที่ถูกขายไปแล้วไม่ปรากฏในรายการให้เลือก", prio="Medium"),
    dict(id="TC-B1-04", scenario="ราคาต่อ CBM คำนวณถูกต้อง (regression พื้นฐาน)",
         pre="Block มี Cost / CBM ที่ทราบค่าแน่นอน",
         steps=["เลือก Block เข้า SO line", "ตรวจราคาต่อหน่วยที่ระบบตั้งให้"],
         sample="Cost / CBM ของ Block = 15,000",
         expected="ราคาต่อหน่วยตรงตามสูตรต้นทุน/ราคาขายต่อ CBM ของ Block ไม่ผิดเพี้ยน", prio="Medium"),
  ]),
  dict(cat_id="B2", title="B2. Mode 2 — Ready-Made Slab (Serial / Lot)",
       subtitle="ADR-002/006/009/020 — เลือกทีละแผ่น vs เลือกเป็นจำนวนตร.ม. · 4 test cases",
       cases=[
    dict(id="TC-B2-01", scenario="Material โหมด Serial — เลือกแผ่นเฉพาะเจาะจงหลายแผ่น",
         pre="Material เป็นโหมด Serial มีแผ่นสถานะ Available หลายแผ่น",
         steps=["เปิด SO เพิ่มบรรทัด กด \"Select Slabs\"", "เลือกหลายแผ่นพร้อมกันตามหมายเลขกำกับ", "กด \"Confirm Selection\""],
         sample="เลือก 2-3 แผ่นจากรายการที่สถานะ Available",
         expected="บรรทัด SO ผูกแผ่นครบตามที่เลือก แต่ละแผ่นเปลี่ยนสถานะเป็น Hold", prio="High"),
    dict(id="TC-B2-02", scenario="Material โหมด Lot — ระบุจำนวนตร.ม.บางส่วน",
         pre="Material เป็นโหมด Lot มี Block ที่มีสต็อกรวมเพียงพอ",
         steps=["เปิด SO เพิ่มบรรทัดสินค้า Material นี้ กด \"Select Lot Stock\"", "กรอก Quantity to Sell (Sq.Mt.) เป็นจำนวนบางส่วนจาก Lot", "กด \"Confirm Selection\""],
         sample="Quantity to Sell (Sq.Mt.) = 5.0 (น้อยกว่า Remaining Sqmt ของ Lot ทั้งก้อน)",
         expected="บรรทัด SO ผูก Lot ถูกต้อง ไม่มีการเลือกแผ่นเดี่ยวใดๆ (ปุ่ม Select Slabs ไม่เกี่ยวข้องกับโหมดนี้)", prio="High"),
    dict(id="TC-B2-03", scenario="แก้ไขบรรทัด SO ที่ส่งแผ่นไปแล้ว",
         pre="บรรทัด SO นี้ส่งแผ่นไปแล้วอย่างน้อย 1 แผ่น",
         steps=["เปิด \"Select Slabs\" บนบรรทัดนี้อีกครั้งเพื่อลองแก้ไข"],
         sample="-",
         expected="ถูกบล็อกไม่ให้แก้ไขรายการแผ่นอีก", prio="Medium"),
    dict(id="TC-B2-04", scenario="Regression: ตั้งราคาเอง แล้วค่อยกด Select Slabs ทีหลัง",
         note="หมายเหตุ: ข้อจำกัดที่ทราบอยู่แล้ว — คู่มือบทที่ 12 เตือนไว้",
         pre="บรรทัด SO ยังไม่ได้เลือกแผ่น",
         steps=["พิมพ์ราคาเองในช่อง Unit Price ของบรรทัดก่อน", "กด \"Select Slabs\" เลือกแผ่นทีหลัง", "ตรวจราคาที่ได้"],
         sample="Unit Price ที่พิมพ์เอง = 9,999 (ตัวเลขทดสอบ)",
         expected="ราคาที่ตั้งไว้ก่อนหน้าถูกรีเซ็ตกลับเป็นราคามาตรฐานของสินค้า (พฤติกรรมของ Odoo เอง) — ต้องตั้งราคาเองหลังเลือกแผ่นเสร็จเท่านั้น", prio="Medium"),
  ]),
  dict(cat_id="B3", title="B3. Mode 3 — Cut-to-Order (MRP)",
       subtitle="ADR-018 — ตัดแผ่นใหม่จาก Block ตามสั่ง · 5 test cases",
       cases=[
    dict(id="TC-B3-01", scenario="สร้าง Cut Order ขณะ Block ยังไม่ได้ย้ายไป Stone Production",
         note="หมายเหตุ: ระบบใหม่ (เพิ่ม 2026-08-16) — Block ต้องถูกย้ายไปสถานีตัดก่อนเสมอ",
         pre="Block อยู่ที่ Location \"Stone Available\" เท่านั้น ยังไม่เคยถูกย้ายไป \"Stone Production\"",
         steps=["เปิดหน้าต่าง \"Create Cut Order\" เลือก Block นี้ กรอก Target L / Target H", "กด \"Create Cut Order\""],
         sample="Target L (M) = 1.0<br>Target H (M) = 1.0",
         expected="ระบบฟ้อง error สองภาษาแจ้งว่า Block ยังไม่ได้ย้ายไปสถานีตัด (Stone Production) เพียงพอ พร้อมบอกให้สแกน/ย้าย Block ไปก่อน บันทึกไม่ผ่าน", prio="High"),
    dict(id="TC-B3-02", scenario="ย้าย Block ไป Stone Production ก่อนสร้าง Cut Order", pre="-",
         steps=["ทำ Internal Transfer (ผ่านแอป Inventory หรือ Barcode) ย้าย Block จาก \"Stone Available\" ไป \"Stone Production\"", "เปิดหน้าต่าง \"Create Cut Order\" สร้างใหม่อีกครั้งด้วยขนาดเดิม"],
         sample="Target L (M) = 1.0<br>Target H (M) = 1.0",
         expected="สร้าง Manufacturing Order สำเร็จ ไม่ติด error", prio="High"),
    dict(id="TC-B3-03", scenario="Confirm MO ที่มาจากบรรทัด SO จริง",
         pre="Manufacturing Order มาจาก Cut Order ที่สร้างจากบรรทัด SO ที่ยังไม่มีแผ่นจริง",
         steps=["Confirm Manufacturing Order ให้เสร็จสมบูรณ์", "ตรวจแผ่นใหม่ที่ได้ และรายการ Analytic Account ของ SO"],
         sample="-",
         expected="แผ่นใหม่ถูกผูกเข้ากับบรรทัด SO ที่สั่งไว้ทันที (สถานะ Hold) และค่าแรงประมาณการถูกบันทึกเข้า Analytic Account ของ SO ถูกต้อง", prio="High"),
    dict(id="TC-B3-04", scenario="Block ที่สต็อกถูกจองเต็มไปกับงานอื่นแล้ว — ตัดแผ่นใหม่",
         note="หมายเหตุ: edge case ที่เคยพบ ยังไม่เจอเคสจริงซ้ำแบบเต็มรูปแบบ",
         pre="Block ที่จะตัดถูกจองสต็อกไปกับงานอื่นเต็มจำนวนแล้ว",
         steps=["สร้าง Cut Order และ Confirm Manufacturing Order ตัดแผ่นจาก Block นี้"],
         sample="-",
         expected="ตัดแผ่นสำเร็จ ไม่ขึ้น error \"You need to supply a Lot/Serial Number\" (ยืนยันว่าจุดที่เคยแก้ไว้ยังใช้ได้)", prio="Medium"),
    dict(id="TC-B3-05", scenario="Cut-to-Order ข้ามบริษัท (Block อยู่ Empire Stone, สร้างจาก SO ของ Empire Granite)",
         pre="Block ที่จะตัดอยู่คลังของ Empire Stone แต่ SO เป็นของ Empire Granite",
         steps=["สร้าง Cut Order เลือก Block ของ Empire Stone", "Confirm Manufacturing Order"],
         sample="-",
         expected="BOM/Work Center/Operation Type ที่ใช้ตรงกับบริษัทของคลังที่ Block อยู่จริง (Empire Stone) ไม่สลับบริษัทผิด", prio="High"),
  ]),
  dict(cat_id="B4", title="B4. Mode 4 — Sold-as-Project (BOQ → Project)",
       subtitle="ADR-021/ADR-038 — สร้าง Project + Task (จัดกลุ่มตาม Zone) + Milestone ตามที่เลือกไว้ · 9 test cases",
       cases=[
    dict(id="TC-B4-01", scenario="ติ๊ก \"Sold as Project\" แล้ว Confirm SO",
         pre="SO มีหลายบรรทัด (ไม่ใช่บรรทัด Section/Note ล้วน)",
         steps=["ติ๊ก \"Sold as Project\" บน SO", "กด Confirm", "ตรวจ Project ที่เกิดขึ้น"],
         sample="-",
         expected="ระบบสร้าง Project ให้อัตโนมัติ พร้อม Task 1 ใบต่อบรรทัดสั่งซื้อที่ไม่ใช่ Section/Note", prio="High"),
    dict(id="TC-B4-02", scenario="Task เชื่อมกลับไปยังบรรทัด SO เฉพาะบรรทัดบริการ",
         pre="SO มีทั้งบรรทัดบริการ (แรงงาน) และบรรทัดสินค้าจริง (Material/Block)",
         steps=["Confirm SO แบบ Sold as Project", "เปิด Task ของแต่ละบรรทัดดู"],
         sample="-",
         expected="Task ของบรรทัดบริการมีลิงก์ย้อนกลับไปยัง Sale Order Line เดิม (เห็นได้จากข้อมูล Sales Order บน Task); Task ของบรรทัดสินค้าจริงไม่มีลิงก์นี้", prio="High"),
    dict(id="TC-B4-03", scenario="Task ผูกกับ BOQ Line เสมอ ไม่ว่าประเภทบรรทัดใด",
         pre="Order line มาจาก BOQ (มีข้อมูล BOQ Line ผูกอยู่ ไม่ใช่บรรทัดที่พิมพ์เพิ่มเอง)",
         steps=["Confirm SO แบบ Sold as Project", "เปิด Task ที่ได้ดู"],
         sample="-",
         expected="Task ผูกกับ BOQ Line เดิมเสมอ ไม่ว่าบรรทัดนั้นจะเป็นบริการหรือสินค้าจริง (ต่างจาก Sale Order Line ที่ผูกเฉพาะบรรทัดบริการใน TC-B4-02)", prio="Medium"),
    dict(id="TC-B4-04", scenario="หลาย BOQ Zone/Schedule ในออเดอร์เดียว",
         pre="BOQ มีอย่างน้อย 2 Zone/Schedule (เช่น \"L4 Main Lobby\" และ \"L5 Skylounge\")",
         steps=["Confirm SO แบบ Sold as Project", "ตรวจวันเริ่ม/วันกำหนดส่งของ Task แต่ละ Zone"],
         sample="-",
         expected="Task ถูกจัดกลุ่มแยกตาม Zone เรียงลำดับกันภายใน Zone ตามลำดับที่ตั้งไว้ในบรรทัด BOQ และแต่ละ Zone เริ่มนับวันที่ \"วันนี้\" พร้อมกัน (ไม่ต่อคิวข้าม Zone)", prio="High"),
    dict(id="TC-B4-05", scenario="บรรทัดที่พิมพ์เพิ่มเองนอกเหนือจาก BOQ",
         pre="SO มีบรรทัดที่พิมพ์เพิ่มเองนอกเหนือจากที่มาจาก BOQ",
         steps=["Confirm SO แบบ Sold as Project", "ตรวจวันที่ของ Task บรรทัดนี้"],
         sample="-",
         expected="ได้กำหนดการแบบ placeholder เดียวกันเสมอ (วันนี้ → +1 วัน) เพราะไม่มี Zone/ลำดับจาก BOQ ให้อ้างอิง", prio="Low"),
    dict(id="TC-B4-06", scenario="BOQ Line ที่ติ๊ก Milestone ไว้",
         pre="BOQ มีบางบรรทัดติ๊กช่อง Milestone ไว้ บางบรรทัดไม่ติ๊ก",
         steps=["Confirm SO แบบ Sold as Project", "เปิด Project ที่ได้ กด \"Milestones\" (smart button)"],
         sample="-",
         expected="บรรทัดที่ติ๊ก Milestone ไว้ ได้ Milestone ผูกกับ Task ของบรรทัดนั้น 1 ต่อ 1; บรรทัดที่ไม่ติ๊กไม่มี Milestone เกิดขึ้น", prio="High"),
    dict(id="TC-B4-07", scenario="ติ๊ก \"Sold as Project\" หลัง Confirm ไปแล้ว (idempotent)",
         pre="SO confirm ไปแล้วโดยไม่ได้ติ๊ก \"Sold as Project\" ตอนแรก",
         steps=["ติ๊ก \"Sold as Project\" ทีหลัง", "กดปุ่ม \"สร้าง Project\" ที่ปรากฏขึ้น"],
         sample="-",
         expected="Project ถูกสร้างสำเร็จ และปุ่ม \"สร้าง Project\" หายไปหลังจากนั้น (เพราะมี Project ผูกอยู่แล้ว) กดสร้างซ้ำซ้อนอีกไม่ได้", prio="Medium"),
    dict(id="TC-B4-08", scenario="บรรทัดเสริม \"Overhead &amp; Profit\" จาก BOQ",
         note="หมายเหตุ: พบ 2026-08-16 — flagged ไว้ ยังไม่ปรับแก้",
         pre="เอกสาร BOQ มีบรรทัดเสริม \"Overhead &amp; Profit\" ที่ระบบสร้างให้อัตโนมัติ",
         steps=["Confirm SO ที่มีบรรทัดนี้แบบ Sold as Project", "ตรวจ Task ทั้งหมดที่เกิดขึ้น"],
         sample="-",
         expected="บรรทัดเสริมนี้ก็ได้ Task ของตัวเองเช่นกัน (ยังไม่ถูกกรองทิ้ง — สถานะที่ทราบอยู่แล้ว ต้อง verify ว่ายังตรงกับที่ทีมต้องการ)", prio="Low"),
    dict(id="TC-B4-09", scenario="Regression: Backfill Milestone หลัง Project สร้างไปแล้ว",
         pre="Project สร้างไปแล้ว แล้วมี BOQ Line ถูกติ๊ก Milestone เพิ่มทีหลัง (รวมถึงกรณีชื่อบรรทัดซ้ำกันข้าม Section เช่น \"Dry-Lay\" ที่ปรากฏทั้งใน JOB A และ JOB B)",
         steps=["ติ๊ก Milestone เพิ่มบน BOQ Line ที่ยังไม่มี Milestone", "เปิด SO กดปุ่ม \"สร้าง Milestone ใหม่\""],
         sample="-",
         expected="Milestone ใหม่ถูกสร้างและจับคู่กับ Task ที่ถูกต้องแม่นยำ แม้มี 2 บรรทัด BOQ ชื่อซ้ำกันข้าม Section ก็ตาม", prio="Medium"),
  ]),
  dict(cat_id="B5", title="B5. Mode 5 — Stone Production / FG Production",
       subtitle="ADR-029 — ตัด Slab แล้วผลิตต่อเป็นสินค้าสำเร็จรูป (FG) · 4 test cases",
       cases=[
    dict(id="TC-B5-01", scenario="Confirm SO ขายสินค้า FG",
         pre="มีสินค้า FG ที่ตั้ง BOM ไว้แล้ว (หรือยังไม่เคยผลิต — ระบบจะสร้างให้อัตโนมัติ)",
         steps=["Confirm SO ที่มีบรรทัดขายสินค้า FG", "ตรวจ Manufacturing Order ที่เกิดขึ้น"],
         sample="-",
         expected="ระบบขึ้นคิวงานผลิต (Manufacturing Order) ให้อัตโนมัติ โดยใช้ Slab ของ Material ต้นทางเป็นวัตถุดิบ", prio="High"),
    dict(id="TC-B5-02", scenario="ยังไม่มี Slab จริงในสต็อกสำหรับ FG นี้",
         pre="Slab ต้นทางยังไม่ถูกตัดไว้เลย",
         steps=["Confirm SO ขาย FG", "ตรวจลำดับ Manufacturing Order/ขั้นตอนที่ระบบสร้าง"],
         sample="-",
         expected="ระบบสร้างลำดับงาน 2 ขั้นตอนต่อกัน: ตัด Slab ก่อน แล้วจึงผลิต FG ตามหลัง เรียงลำดับถูกต้อง", prio="Medium"),
    dict(id="TC-B5-03", scenario="Confirm การผลิต FG จริง",
         pre="Manufacturing Order ผลิต FG พร้อม Confirm",
         steps=["Confirm Manufacturing Order ผลิต FG ให้เสร็จ", "ตรวจสต็อกสินค้า FG ที่ได้"],
         sample="-",
         expected="ได้สต็อกสินค้า FG จริง แยกชุดการผลิตแต่ละครั้งได้ (Lot/Serial แยกกัน)", prio="High"),
    dict(id="TC-B5-04", scenario="FG variant+Company คู่ใหม่ที่ยังไม่เคยผลิต",
         pre="Product Category ของสินค้า FG ตั้งรายการขั้นตอนงาน (เช่น Polishing, Edge) เรียงลำดับไว้แล้ว",
         steps=["สั่งผลิตสินค้า FG นี้ครั้งแรกจากบริษัทหนึ่ง", "ตรวจขั้นตอนงานของ Manufacturing Order/BOM ที่ได้"],
         sample="-",
         expected="ขั้นตอนงานเรียงตามลำดับที่ตั้งไว้ในหมวดสินค้าครบทุกขั้น", prio="Medium"),
  ]),
  dict(cat_id="B6", title="B6. Intercompany Trade (Empire Granite ↔ Empire Stone)",
       subtitle="cross-cutting ทุกโหมดที่เกี่ยวกับสต็อก — สร้าง SO/PO ภายในอัตโนมัติ · 7 test cases",
       cases=[
    dict(id="TC-B6-01", scenario="ขายแผ่น (Serial) ข้ามบริษัท — Empire Granite ขาย, แผ่นอยู่ Empire Stone",
         pre="แผ่นที่เลือกอยู่คลังของ Empire Stone แต่ SO เป็นของ Empire Granite",
         steps=["เลือกแผ่นของ Empire Stone เข้า SO ของ Empire Granite ผ่าน \"Select Slabs\"", "Confirm SO"],
         sample="-",
         expected="ระบบสร้าง SO ภายใน (Empire Stone ขาย Empire Granite) และ PO ภายใน (Empire Granite ซื้อจาก Empire Stone) ให้อัตโนมัติ พร้อมบวก Markup ตามที่ตั้งไว้ในค่า \"Stone Intercompany Markup %\" ของ Empire Stone (Settings &gt; Companies)", prio="High"),
    dict(id="TC-B6-02", scenario="SO/PO ภายในต้อง Confirm + ออกใบแจ้งหนี้อัตโนมัติ",
         pre="ต่อเนื่องจาก TC-B6-01",
         steps=["ตรวจ SO ภายในและ PO ภายในที่เกิดขึ้น"],
         sample="-",
         expected="ทั้งคู่ถูก Confirm ให้อัตโนมัติ พร้อมสร้างใบแจ้งหนี้ (SO)/ใบเรียกเก็บจากผู้ขาย (PO) ทันที ไม่ค้างสถานะ Draft ให้ต้องทำมือ", prio="High"),
    dict(id="TC-B6-03", scenario="รายการส่งของเดิมของบริษัทผู้ซื้อถูกตัดถูกต้อง",
         pre="ต่อเนื่องจาก TC-B6-01 (ก่อน Confirm มีรายการรอส่งของ Empire Granite ค้างอยู่ก่อน)",
         steps=["ตรวจรายการรับ-ส่งของของ Empire Granite หลัง Confirm"],
         sample="-",
         expected="ส่วนที่เป็นแผ่นข้ามบริษัทถูกตัด/ปรับออกจากรายการเดิมอย่างถูกต้อง ไม่มีรายการค้างครึ่งๆ กลางๆ", prio="Medium"),
    dict(id="TC-B6-04", scenario="ขายแบบ Lot ข้ามบริษัท",
         pre="Block เป็นโหมด Lot อยู่ Empire Stone, SO เป็นของ Empire Granite ระบุจำนวนตร.ม.บางส่วน",
         steps=["Confirm SO"],
         sample="-",
         expected="SO/PO ภายในใช้ Slab Product (ไม่ใช่ Block Product) และราคาอิงตาม Cost / Sq.Mt. บวก Markup", prio="High"),
    dict(id="TC-B6-05", scenario="ขายทั้งก้อน (Block) ข้ามบริษัท",
         pre="Block อยู่ Empire Stone, SO เป็นของ Empire Granite (Mode 1)",
         steps=["Confirm SO"],
         sample="-",
         expected="SO/PO ภายในใช้ Block Product และราคาอิงตาม Cost / CBM บวก Markup", prio="High"),
    dict(id="TC-B6-06", scenario="หลายแผ่นข้ามบริษัทจากคนละบริษัทผู้ขายในออเดอร์เดียว",
         pre="SO เดียวมีแผ่นข้ามบริษัทจากอย่างน้อย 2 บริษัทผู้ขายที่ต่างกัน",
         steps=["Confirm SO ที่มีแผ่นข้ามบริษัทจากคนละบริษัทผู้ขาย"],
         sample="-",
         expected="ระบบแยก SO/PO ภายในเป็นคนละชุดตามบริษัทผู้ขายอย่างถูกต้อง ไม่ปนกัน", prio="Medium"),
    dict(id="TC-B6-07", scenario="Regression: SO ที่ไม่ข้ามบริษัทเลย",
         pre="Block ทุกรายการใน SO อยู่บริษัทเดียวกับ SO เอง",
         steps=["Confirm SO ปกติ (Mode 1/2/3 อย่างใดอย่างหนึ่ง)"],
         sample="-",
         expected="ไม่มี SO/PO ภายในเกิดขึ้นเลย", prio="High"),
  ]),
  dict(cat_id="B7", title="B7. Cancel / Release Hold",
       subtitle="ปุ่ม Cancel บน SO คืนสถานะแผ่นที่ค้าง Hold · 2 test cases",
       cases=[
    dict(id="TC-B7-01", scenario="Cancel SO ที่มีแผ่นสถานะ Hold ผูกอยู่",
         pre="SO มีแผ่นที่ถูกเลือกไว้แล้ว (สถานะ Hold) ยังไม่ Confirm หรือ Confirm แล้วแต่ยังไม่ส่งของ",
         steps=["กด Cancel บน SO", "ตรวจสถานะแผ่นที่เคยผูกอยู่"],
         sample="-",
         expected="แผ่นกลับสถานะเป็น Available ฟิลด์ Customer และ Sale Order บนแผ่นนั้นถูกล้างค่าว่างเปล่า", prio="High"),
    dict(id="TC-B7-02", scenario="Cancel SO ที่ไม่มีแผ่นค้าง Hold เลย",
         pre="SO เป็น Mode 4 ล้วน (ไม่มีสินค้าที่ผูกกับแผ่นหิน)",
         steps=["กด Cancel บน SO"],
         sample="-",
         expected="ทำงานปกติ ไม่ error แม้ไม่มีแผ่นให้ปล่อยคืน", prio="Low"),
  ]),
  dict(cat_id="B8", title="B8. Multi-Company Visibility &amp; Security",
       subtitle="กลุ่มสิทธิ์ EMG-O Internal User/Manager + การเข้าถึงข้ามบริษัท · 4 test cases",
       cases=[
    dict(id="TC-B8-01", scenario="ผู้ใช้ที่มีสิทธิ์เข้าถึงหลายบริษัทเห็นข้อมูลทั้ง 2 บริษัท",
         pre="ผู้ใช้ (เช่น emgdemo) มีสิทธิ์เข้าถึงทั้ง Empire Granite และ Empire Stone",
         steps=["Login ด้วยผู้ใช้นี้", "เปิดรายการ Stone Block/Slab"],
         sample="-",
         expected="เห็นข้อมูลทั้ง 2 บริษัทพร้อมกันโดยไม่ต้องสลับตัวเลือกบริษัทที่มุมขวาบน", prio="Medium"),
    dict(id="TC-B8-02", scenario="ผู้ใช้ที่ล็อกอินอยู่บริษัทเดียว — Hold/Release แผ่นข้ามบริษัท",
         note="หมายเหตุ: เคยพบบั๊กจุดนี้มาก่อน (แก้แล้ว 2026-07-22)",
         pre="ผู้ใช้เลือกบริษัทที่ใช้งานอยู่แค่บริษัทเดียว (ไม่ได้เลือกหลายบริษัทพร้อมกันที่ตัวสลับบริษัท) แต่มีสิทธิ์เข้าถึงทั้ง 2 บริษัท",
         steps=["ทำ \"Select Slabs\" เลือกแผ่นที่อยู่อีกบริษัทหนึ่ง ผ่านขั้นตอนปกติของ SO"],
         sample="-",
         expected="ไม่ติด Access Error ตอนเปิดดูคลัง/ทำเลของอีกบริษัท", prio="High"),
    dict(id="TC-B8-03", scenario="ผู้ใช้ที่ไม่มีสิทธิ์กลุ่ม EMG-O เลย",
         pre="ผู้ใช้ไม่มีทั้งสิทธิ์ \"EMG-O Internal User\" และ \"EMG-O Internal Manager\"",
         steps=["Login ด้วยผู้ใช้นี้", "มองหาเมนู Stone Material/Block/Slab"],
         sample="-",
         expected="ไม่เห็นเมนู EMG-O เลย หรือถูกฟ้อง Access Error ตามสิทธิ์ที่ควรเป็น", prio="Medium"),
    dict(id="TC-B8-04", scenario="Regression: ผู้ใช้ที่มีแค่สิทธิ์ \"EMG-O Internal User\" ต้อง Login เข้าหลังบ้านได้",
         note="หมายเหตุ: เคยพบบั๊กเข้าหลังบ้านไม่ได้มาก่อน (แก้แล้ว 2026-08-15)",
         pre="ผู้ใช้ใหม่ที่มีสิทธิ์เฉพาะ \"EMG-O Internal User\" (ไม่มีสิทธิ์กลุ่มอื่นเพิ่ม)",
         steps=["Login ด้วยผู้ใช้นี้เข้าหน้าระบบหลังบ้าน"],
         sample="-",
         expected="เข้าหน้าระบบหลังบ้านได้ปกติเหมือน internal user ทั่วไป ไม่ใช่ถูกจำกัดสิทธิ์แบบ portal user", prio="High"),
  ]),
]

if __name__ == '__main__':
    total = sum(len(c['cases']) for c in CATEGORIES)
    prios = {'High': 0, 'Medium': 0, 'Low': 0}
    for c in CATEGORIES:
        for tc in c['cases']:
            prios[tc['prio']] += 1
    print('Total test cases:', total)
    print('Priority breakdown:', prios)
    print('Categories:', len(CATEGORIES))
