# Single source of truth for EMG-O QA test cases: Day-in-the-Life
# (full order-to-cash regression walkthrough, Mode 4 — Sold as Project).
#
# v2 (2026-08-27): rewritten to cover EVERY beat of the client-facing
# "day-in-the-life.html" demo (presentations/day-in-life.html, slides 2-11b)
# end to end in ONE golden-thread narrative, not just the accounting layer
# that test-cases-product-sales.html didn't already have. Cases that overlap
# ground already covered there (Material setup ~ A1-A4, BOQ->Project/Task/
# Milestone ~ B4, Cut Order ~ A6/A7/B3) are deliberately RE-TESTED here too,
# each subtitle marked "(regression of <old category>)" — this document's
# purpose is to catch drift in a real end-to-end run, not to avoid
# duplicating the feature-level suite. Categories follow the exact 9-stage
# flow-bar the demo itself uses: Setup Product -> ผูก Analytic -> เสนอราคา ->
# มัดจำ -> เบิก Block -> ตัดหิน -> ค่าใช้จ่ายหน้างาน -> ติดตั้ง/ปิดยอด -> ดู P&L.
#
# Re-verified against source 2026-08-27 (odoo19-ent-mbx/addons) — notably:
#   - D1-03 (Density -> Weight(Ton) auto-fill): stone_bundle.py
#     _onchange_weight_ton(), added 2026-08-25 — genuinely new ground, not in
#     A2/A3 of the old suite at all.
#   - D6-03 (2-plan simultaneous Analytic tagging on cutting labor cost):
#     mrp_production.py _split_analytic_distribution()/_tag_stone_cutting_
#     labor_cost() — the multi-plan-per-line comma-join handling was ADDED
#     2026-08-26 (ONE DAY before this doc was written). High regression risk,
#     flagged as such.
#   - D8-01 (Task Done -> Milestone auto-reach): boq_estimation/models/
#     project_task.py write() override — only fires when the linked
#     Milestone has exactly 1 Task (len(m.task_ids) == 1); noted in
#     precondition, not assumed.
#   - D5 (real cost from PO on Block): stone_bundle.py po_cost_sqmt/cbm +
#     landed_cost_sqmt/cbm + cost_sqmt/cbm = po_cost + landed_cost.
#   - D8-03/04 (WHT): account_move.py has_wht compute + button
#     "Print WHT Certificate" (header, visible only when has_wht and
#     state == 'posted').
#   - D2/D9 (Analytic Distribution Models / Chart of Analytic Accounts /
#     Gross Margin): NATIVE Odoo Enterprise Accounting, not custom code —
#     what's actually at risk is whether this module's auto-created lines
#     carry the analytic tag through, not the native feature itself.
#   - D4/D7 (Down Payment invoicing, vendor-bill Analytic Distribution,
#     final-invoice deposit reversal): also NATIVE Odoo, no custom code
#     found anywhere in this module for deposit/percentage handling.
#
# Column model per test case (same as qa_data.py):
#   id, scenario, note (optional amber callout), pre, steps (list),
#   sample (str, the "key this in" data - '-' if the case has nothing to key),
#   expected, prio (High/Medium/Low)

CATEGORIES = [
  dict(cat_id="D1", title="D1. Setup Product — Material, Pricing Mode, Density, Costing",
       subtitle="regression ของหมวด A1-A4 เดิม + Density (ฟีเจอร์ใหม่ 25 ส.ค.) · 8 test cases",
       cases=[
    dict(id="TC-D1-01", scenario="สร้าง Material ใหม่ผ่าน Quick Material Setup Wizard (สร้าง Slab + Block Product ให้อัตโนมัติ)",
         note="regression ของ TC-A1-01 — ปรับ flow ให้ตรงกับ day-in-life.html สไลด์ 2 จริง (ใช้ wizard ไม่ใช่ฟอร์ม Material ตรงๆ ซึ่งต้องมี Slab Product อยู่ก่อนแล้วถึงจะเลือกได้ ไม่เหมาะกับ Material ใหม่เอี่ยม) — ⚠️ ต้องมีสิทธิ์ Products/Create ก่อน (group_emgo_internal_manager ยังไม่มี ณ 2026-08-27 ดู progress.md finding #1) ไม่งั้น wizard จะ error ตอนสร้าง Slab/Block Product นี้เป็น fixture หลัก (\"Test Marble 01\") ที่ TC-D1-02/03/03b/04 ใช้ต่อทั้งหมด",
         pre="ผู้ใช้มีสิทธิ์ EMG-O Internal Manager และมีสิทธิ์ Products/Create",
         steps=["เปิดเมนู Configuration &gt; Quick Material Setup", "เลือก Setup Mode = \"สร้าง Material ใหม่\"", "กรอกทุกฟิลด์ตามคอลัมน์ข้อมูลตัวอย่าง (ติ๊ก \"ขายทั้งก้อนได้ (Block Product)\" ด้วย — จำเป็นสำหรับ TC-D1-03 ต่อไป)", "กด Confirm"],
         sample="Setup Mode = \"สร้าง Material ใหม่\"<br>Material Name = \"Test Marble 01\"<br>Category = \"Marble\"<br>Pricing Mode = \"Serial (per-slab)\"<br>Origin Country = \"Italy\" (optional)<br>Density (Ton/CBM) = 2.75 (optional — ใส่ไว้เพื่อใช้ต่อใน TC-D1-03)<br>Slab Sales Price = 1,500<br>Slab Cost = 1,000<br>ขายทั้งก้อนได้ (Block Product) = ✔ ติ๊ก<br>Block Sales Price = 18,000<br>Block Cost = 15,000<br>มี Finished Good = ไม่ติ๊ก (ทดสอบแยกใน TC-D1-06b)",
         expected="สร้างสำเร็จ ไม่มี error — ระบบสร้าง 2 สินค้าให้อัตโนมัติ: (1) \"Test Marble 01 - Slab\" Tracking=Serial UoM=Unit และ (2) \"Test Marble 01 - Block\" Tracking=Lot UoM=m³ แล้วผูกทั้งคู่เข้ากับ Material ทันที (product_id + product_id_block) เปิด Material ดู Costing Basis จะเป็นค่าเริ่มต้น \"Area (Sq.Mt.)\" เสมอ (wizard ไม่มีฟิลด์นี้ให้กรอกโดยตรง)", prio="High"),
    dict(id="TC-D1-02", scenario="Material มี Block อยู่แล้ว — พยายามเปลี่ยน Pricing Mode",
         note="regression ของ TC-A2-04",
         pre="Material \"Test Marble 01\" มี Block อยู่แล้ว 1 ใบ (สร้างจาก TC-D1-03) — ถ้าทำ TC นี้ก่อน TC-D1-03 ให้สร้าง Block เปล่าๆ ของ Material นี้ไว้ก่อน 1 ใบพอ (Supplier/Warehouse/PO Line อะไรก็ได้ ขอแค่มี stone.bundle ผูกกับ Material นี้จริง)",
         steps=["เปิด Material \"Test Marble 01\"", "เปลี่ยน Pricing Mode จาก \"Serial (per-slab)\" เป็น \"Lot (aggregate, cheap stone)\"", "กด Save"],
         sample="Pricing Mode: \"Serial (per-slab)\" → \"Lot (aggregate, cheap stone)\"",
         expected="บันทึกไม่ผ่าน ขึ้น error ข้อความเป๊ะๆ: \"Pricing Mode ถูกล็อกแล้ว เพราะ Material นี้มี Block อยู่แล้ว — สลับระหว่าง Serial กับ Lot บน Material ที่มีสต็อกจริงจะทำให้สถานะสต็อกปนกันผิดพลาด\"", prio="High"),
    dict(id="TC-D1-03", scenario="สร้าง PO จริง + ยืนยัน แล้วสร้าง Block จาก PO นั้น — Weight (Ton) เติมให้อัตโนมัติจาก Density",
         note="ฟีเจอร์ใหม่ 2026-08-25 ไม่เคยมี Test Case มาก่อน — ⚠️ เพิ่ม field ที่ขาดไปจากเอกสารเดิม: Total CBM/Weight(Ton)/Purchase Order Line/Thickness(M) ทั้งหมด invisible บนฟอร์ม Block ถ้า Material ไม่มี Block Product (ดู stone_bundle_views.xml, group invisible=\"not material_has_block_product\") และ 3 ใน 4 ฟิลด์นั้นเป็น required ทันทีที่ Material มี Block Product — ต้องมี PO จริง (confirm แล้ว) อยู่ก่อนถึงจะสร้าง Block ได้เลย ไม่ใช่กรอก Total CBM ลอยๆ ตามที่เอกสารเดิมเขียนไว้ เพิ่มขั้นตอนสร้าง PO เองในเคสนี้เลย (แทนที่จะสมมติไว้ใน precondition เฉยๆ) เพราะถ้าไม่มี PO จริงจะทดสอบขั้นต่อไปไม่ได้เลย",
         pre="Material \"Test Marble 01\" มี Block Product แล้ว (จาก TC-D1-01) และตั้ง Density=2.75 ไว้แล้ว",
         steps=["เปิดเมนู Purchase &gt; Orders &gt; New", "เลือก Vendor = \"Demo Quarry Co.\"", "กด \"Add a line\" เพิ่มบรรทัด: Product=\"Test Marble 01 - Block\", Quantity=2.0, Unit Price=25,000 (Subtotal เติมอัตโนมัติ=50,000)", "กด \"Confirm Order\" (PO เปลี่ยนสถานะเป็น Purchase)", "เปิดเมนู Stone Slab &gt; Blocks &gt; New", "กรอก Material/Quality/Warehouse", "เลือก Purchase Order Line = บรรทัดของ PO ที่เพิ่งยืนยัน — สังเกต Supplier + Total CBM เติมให้อัตโนมัติทันที", "กรอก Thickness (M)", "ดูช่อง Weight (Ton) โดยไม่ต้องพิมพ์เอง แล้วกด Save"],
         sample="Vendor = \"Demo Quarry Co.\"<br>PO Line: Product=\"Test Marble 01 - Block\", Quantity=2.0, Unit Price=25,000, Subtotal=50,000 (เติมอัตโนมัติ)<br>—<br>Material = \"Test Marble 01\"<br>Quality = \"First\" (ค่าเริ่มต้น)<br>Warehouse = \"Empire Granite Warehouse (EG01)\"<br>Purchase Order Line = บรรทัด PO ที่เพิ่งยืนยัน<br>Supplier = เติมอัตโนมัติ = \"Demo Quarry Co.\"<br>Total CBM = เติมอัตโนมัติ = 2.0<br>Thickness (M) = 0.04",
         expected="PO confirm สำเร็จ (state=Purchase) — ทันทีที่เลือก Purchase Order Line บนฟอร์ม Block: Supplier + Total CBM เติมให้อัตโนมัติ (2.0) แล้ว Weight (Ton) เติมต่อให้อัตโนมัติ = 5.5 (2.0 × 2.75) โดยไม่ต้องพิมพ์เอง บันทึกสำเร็จ (PO+Block นี้ใช้ fixture ต่อใน TC-D1-04 ด้วย)", prio="Medium"),
    dict(id="TC-D1-03b", scenario="แก้ Weight (Ton) มือหลังระบบเติมให้แล้ว (ค่าจากตาชั่งจริง)",
         note="ฟีเจอร์ใหม่ 2026-08-25 — ตรวจว่าไม่ถูกเขียนทับจนกว่าจะแก้ Total CBM หรือ Material อีกครั้ง",
         pre="Block จาก TC-D1-03 มี Weight (Ton) เติมอัตโนมัติแล้ว = 5.5",
         steps=["เปิด Block จาก TC-D1-03", "แก้ Weight (Ton) เป็นค่าจากตาชั่งจริงด้วยมือ", "กด Save โดยไม่แตะ Total CBM หรือ Material อีก"],
         sample="Weight (Ton) = 5.65 (ค่าจริงจากตาชั่ง ต่างจากค่าคำนวณ 5.5)",
         expected="ค่าที่กรอกมือถูกเก็บไว้ตามที่พิมพ์ (5.65) ไม่ถูกคำนวณทับกลับเป็น 5.5", prio="Low"),
    dict(id="TC-D1-04", scenario="Costing Basis = Area (ค่าเริ่มต้น) คำนวณ Cost ของแผ่นถูกต้อง จากต้นทุนจริงของ PO",
         note="regression ของ TC-A3-04 — ⚠️ แก้จากเอกสารเดิม: cost_sqmt/po_cost_sqmt เป็น compute field (ADR-005, 2026-08-02) ไม่ใช่ช่องให้พิมพ์ตรงๆ อย่างที่เอกสารเดิมสมมติ ต้องมาจากสูตร po_cost_cbm(=PO Subtotal÷Total CBM) × Thickness(M) จริง — ปรับ field ให้ครบเพื่อให้ได้ Cost/Sq.Mt.=1,000 เท่าเดิม",
         pre="Block จาก TC-D1-03 (PO Subtotal=50,000 ÷ Total CBM=2.0 = PO Cost/CBM 25,000 × Thickness 0.04m = PO Cost/Sq.Mt. 1,000; ไม่มี Container ผูก จึง Landed Cost/Sq.Mt.=0 → Cost/Sq.Mt. รวม = 1,000)",
         steps=["เปิด Block จาก TC-D1-03 &gt; แท็บ Slabs &gt; เพิ่ม 1 แถว ระบุ Slab L / Slab H", "ตรวจ Cost ของแผ่นที่ได้"],
         sample="Slab L (M) = 2.0<br>Slab H (M) = 1.5<br>(Cost/Sq.Mt. ของ Block = 1,000 — คำนวณอัตโนมัติจาก PO ไม่ต้องกรอกเอง ดู precondition)",
         expected="Cost = 3,000 (Slab Sq.Mt. 3.0 × Cost/Sq.Mt. 1,000)", prio="High"),
    dict(id="TC-D1-05", scenario="สร้าง Material ใหม่ผ่านฟอร์ม Materials ตรงๆ (ไม่ใช่ Wizard) โดยผูก Slab Product ที่มีอยู่แล้ว — Control Policy เดิมเป็น \"Received quantities\"",
         note="regression ของ TC-A4-01 — กันบิลได้ยอด 0 เพราะไม่เคยยืนยันใบรับสินค้าจริง — ⚠️ ต้องใช้เมนู Configuration &gt; Materials &gt; New ตรงๆ เท่านั้น ห้ามใช้ Quick Material Setup Wizard เพราะ wizard สร้าง Slab Product ใหม่ให้เสมอ ไม่รองรับการเลือกสินค้าที่มีอยู่แล้ว — fixture นี้ (\"Test Onyx 01\") แยกจาก \"Test Marble 01\" เพื่อไม่ให้ชนกับ Block Product ที่ D1-01 สร้างให้ไปแล้ว",
         pre="มีสินค้า \"Test Onyx Slab (Pre-existing)\" สร้างไว้ล่วงหน้าแล้ว (Sales &gt; Products &gt; New: Product Type=Goods, Track Inventory=✔, Tracking=By Unique Serial Number, UoM=Unit, Control Policy แท็บ Purchase = \"Received quantities\")",
         steps=["เปิดเมนู Configuration &gt; Materials &gt; New", "กรอก Material Name/Category/Pricing Mode", "ผูก Slab Product = \"Test Onyx Slab (Pre-existing)\"", "กด Save", "เปิดสินค้านั้นอีกครั้งดูแท็บ Purchase"],
         sample="Material Name = \"Test Onyx 01\"<br>Category = \"Other\"<br>Pricing Mode = \"Serial (per-slab)\"<br>Slab Product = \"Test Onyx Slab (Pre-existing)\" (Control Policy เดิม = \"Received quantities\")",
         expected="บันทึกสำเร็จ ไม่มี error — เปิดสินค้า \"Test Onyx Slab (Pre-existing)\" อีกครั้ง Control Policy (แท็บ Purchase) ถูกเปลี่ยนเป็น \"Ordered quantities\" ให้อัตโนมัติ", prio="High"),
    dict(id="TC-D1-06", scenario="ผูก Block Product ที่มีอยู่แล้วให้ Material เดียวกัน (Fixture B) — Control Policy เดิมเป็น \"Received quantities\"",
         note="regression เบา ของ TC-A4-02 — Block Product เป็นตัวเลือกเสริม หลักการเดียวกับ Slab Product (TC-D1-05) — ⚠️ แยก FG ออกเป็น TC-D1-06b ต่างหากแล้ว เพราะพฤติกรรมจริงต่างกัน ไม่ใช่กรณีเดียวกับ Slab/Block",
         pre="Material \"Test Onyx 01\" จาก TC-D1-05 มีอยู่แล้ว (Slab Product ผูกครบ) และมีสินค้าอีกตัว \"Test Onyx Block (Pre-existing)\" ตั้ง Control Policy เดิม = \"Received quantities\" ไว้ล่วงหน้า",
         steps=["เปิด Material \"Test Onyx 01\"", "ผูก Block Product = \"Test Onyx Block (Pre-existing)\"", "กด Save", "เปิดสินค้านั้นดูแท็บ Purchase"],
         sample="Block Product = \"Test Onyx Block (Pre-existing)\" (Control Policy เดิม = \"Received quantities\")",
         expected="Control Policy ของ Block Product ถูกเปลี่ยนเป็น \"Ordered quantities\" ให้อัตโนมัติ (เหมือน Slab Product ใน TC-D1-05)", prio="Medium"),
    dict(id="TC-D1-06b", scenario="ผูก Finished Good Product (stone_is_fg) เข้ากับ Material — Control Policy ไม่ถูกแก้ให้อัตโนมัติ (ต่างจาก Slab/Block)",
         note="⚠️ เอกสารเดิมเข้าใจผิดว่า FG Product ถูก auto-fix Control Policy เหมือน Slab/Block — เช็คโค้ดจริงแล้ว stone_material.py._ensure_purchase_method() ครอบคลุมเฉพาะ product_id/product_id_block เท่านั้น product_template.py._ensure_stone_fg_tracking() (ทำงานตอนติ๊ก stone_is_fg) จัดการแค่ Tracking/Track Inventory ไม่แตะ Control Policy เลย — แก้ expected result ให้ตรงกับโค้ดจริง ไม่ใช่การเปลี่ยนพฤติกรรม",
         pre="Material \"Test Onyx 01\" มีอยู่แล้ว และมีสินค้าอีกตัว \"Test Onyx FG (Pre-existing)\" ตั้ง Control Policy เดิม = \"Received quantities\" ไว้ล่วงหน้า (ยังไม่ติ๊ก stone_is_fg)",
         steps=["เปิดสินค้า \"Test Onyx FG (Pre-existing)\" (Sales &gt; Products)", "ติ๊ก \"Is Stone FG Product\"", "เลือก \"FG Raw Material\" = Material \"Test Onyx 01\"", "กด Save", "ดูแท็บ Purchase อีกครั้ง"],
         sample="FG Raw Material = \"Test Onyx 01\"",
         expected="Save สำเร็จ — Tracking ถูกบังคับเป็น \"By Lots\" และ Track Inventory ติดอัตโนมัติ แต่ Control Policy (แท็บ Purchase) ยังเป็น \"Received quantities\" เดิม ไม่ถูกเปลี่ยน — ต่างจาก Slab/Block ที่ auto-fix ให้ (ความเสี่ยง: ถ้า FG ตัวนี้เคยซื้อขายจริงและไม่เคย confirm ใบรับสินค้า จะออกบิลได้ยอด 0 — ยังไม่ถูกแก้ในโค้ด)", prio="Medium"),
  ]),
  dict(cat_id="D2", title="D2. ผูก Analytic Distribution Model กับสินค้าหิน",
       subtitle="Native Odoo — ผูกครั้งเดียวต่อหิน 1 ชนิด ทุกยอดขายติดป้ายให้เองอัตโนมัติ · 4 test cases",
       cases=[
    dict(id="TC-D2-01", scenario="สร้าง Analytic Distribution Model ผูกสินค้าหินกับ Account ประเภทวัสดุ 100%",
         pre="มี Analytic Plan \"ประเภทวัสดุ\" และ Analytic Account เช่น \"Granite\"/\"Marble\" ตั้งไว้แล้ว",
         steps=["Accounting &gt; Configuration &gt; Analytic Distribution Models &gt; New", "เลือก Product = สินค้าหิน", "ในบรรทัด Analytic ผูก Plan \"ประเภทวัสดุ\" = Account ที่ตรงกับหินชนิดนั้น 100%", "กด Save"],
         sample="Product = \"Bianco Sardo Granite - Slab\"<br>Analytic Plan \"ประเภทวัสดุ\" = \"Granite\" 100%",
         expected="บันทึกสำเร็จ Model ปรากฏในรายการ Analytic Distribution Models", prio="Medium"),
    dict(id="TC-D2-02", scenario="ขายสินค้าที่ผูก Analytic Distribution Model ไว้แล้ว",
         pre="สินค้ามี Analytic Distribution Model ผูกไว้แล้วตาม TC-D2-01",
         steps=["เปิดใบเสนอราคาใหม่ เพิ่มบรรทัดขายสินค้านั้น", "เปิดดู Analytic Distribution ของบรรทัด (แถบ/ไอคอน Analytic ใต้ราคาแต่ละบรรทัด)"],
         sample="เพิ่มสินค้า \"Bianco Sardo Granite - Slab\" จำนวน 1 หน่วย",
         expected="บรรทัดขายติดป้าย Analytic Account \"Granite\" 100% ให้อัตโนมัติ โดยไม่ต้องเลือกมือ", prio="High"),
    dict(id="TC-D2-03", scenario="สินค้าหินที่ยังไม่ได้ผูก Analytic Distribution Model เลย",
         pre="สินค้าอีกตัวหนึ่งยังไม่เคยตั้ง Analytic Distribution Model",
         steps=["เพิ่มบรรทัดขายสินค้านั้นในใบเสนอราคา", "เปิดดู Analytic Distribution ของบรรทัด"],
         sample="เพิ่มสินค้าที่ยังไม่เคยผูก Analytic Distribution Model",
         expected="บรรทัดขายไม่มี Analytic Account ติดมาให้ ต้องเลือกมือเอง ระบบไม่ error", prio="Medium"),
    dict(id="TC-D2-04", scenario="แก้ % ของ Analytic Distribution Model ภายหลัง ไม่กระทบเอกสารเก่า",
         pre="มีใบเสนอราคาเก่าที่เคยติดป้าย Analytic ไปแล้วตาม Model เดิม",
         steps=["แก้ % ใน Analytic Distribution Model เป็นค่าอื่น", "เปิดใบเสนอราคาเก่าที่เคยติดป้ายไปแล้วดูอีกครั้ง", "เปิดใบเสนอราคาใหม่ เพิ่มสินค้าเดียวกัน แล้วดูป้าย Analytic ที่ได้"],
         sample="เปลี่ยนสัดส่วนเป็น Granite 70% / Overhead 30%",
         expected="ใบเสนอราคาเก่ายังคงค่า Analytic เดิม ไม่เปลี่ยนตาม; ใบเสนอราคาใหม่ได้ค่า Analytic ตาม Model ที่แก้ล่าสุด", prio="Low"),
  ]),
  dict(cat_id="D3", title="D3. ลูกค้าขอใบเสนอราคา — สร้างจาก BOQ ทีละหมวดงาน",
       subtitle="BOQ &gt; สร้างใบเสนอราคา · 2 test cases",
       cases=[
    dict(id="TC-D3-01", scenario="สร้างใบเสนอราคาจาก BOQ ที่มีหลายหมวดงาน",
         pre="มีเอกสาร BOQ ที่ประเมินราคาครบทุกหมวด (วัสดุ/ค่าแรงตัด/ขนส่ง/ค่าแรงติดตั้ง/OH&amp;P) แล้ว",
         steps=["เปิดเอกสาร BOQ", "กดปุ่มสร้างใบเสนอราคา", "ตรวจบรรทัดที่ได้ในใบเสนอราคา"],
         sample="BOQ มีบรรทัด: วัสดุหิน 9,900 / ค่าแรงตัด-ผลิต 3,000 / ค่าขนส่งหน้างาน 2,500 / ค่าแรงติดตั้งหน้างาน 5,000 / Overhead &amp; Profit 1,790",
         expected="ใบเสนอราคาได้บรรทัดครบตามหมวดใน BOQ ยอดรวมตรงกับที่ประเมินไว้ทุกบาท", prio="High"),
    dict(id="TC-D3-02", scenario="บรรทัดวัสดุหินในใบเสนอราคาได้ Analytic ติดมาจาก D2 อัตโนมัติ",
         pre="สินค้าวัสดุหินใน BOQ นี้มี Analytic Distribution Model ผูกไว้แล้ว (TC-D2-01)",
         steps=["สร้างใบเสนอราคาจาก BOQ", "เปิดดู Analytic Distribution ของบรรทัดวัสดุหิน"],
         sample="-",
         expected="บรรทัดวัสดุหินติดป้าย Analytic ประเภทวัสดุให้เองจากขั้นตอนสร้างใบเสนอราคา ไม่ต้องเลือกมือซ้ำ", prio="Medium"),
  ]),
  dict(cat_id="D4", title="D4. ลูกค้าตอบรับ → ยืนยัน SO → สร้าง Project + วางมัดจำ",
       subtitle="regression ของหมวด B4 เดิม (Project/Task/Milestone) + Native Odoo Down Payment · 4 test cases",
       cases=[
    dict(id="TC-D4-01", scenario="ติ๊ก \"Sold as Project\" แล้ว Confirm SO",
         note="regression ของ TC-B4-01",
         pre="SO มีหลายบรรทัด (ไม่ใช่บรรทัด Section/Note ล้วน)",
         steps=["ติ๊ก \"Sold as Project\" บน SO", "กด Confirm", "ตรวจ Project ที่เกิดขึ้น"],
         sample="-",
         expected="ระบบสร้าง Project ให้อัตโนมัติ พร้อม Task 1 ใบต่อบรรทัดสั่งซื้อที่ไม่ใช่ Section/Note", prio="High"),
    dict(id="TC-D4-02", scenario="BOQ Line ที่ติ๊ก Milestone ไว้ได้ Milestone ผูกกับ Task 1:1",
         note="regression ของ TC-B4-06",
         pre="BOQ มีบางบรรทัดติ๊กช่อง Milestone ไว้ บางบรรทัดไม่ติ๊ก",
         steps=["Confirm SO แบบ Sold as Project", "เปิด Project ที่ได้ กด \"Milestones\" (smart button)"],
         sample="-",
         expected="บรรทัดที่ติ๊ก Milestone ไว้ ได้ Milestone ผูกกับ Task ของบรรทัดนั้น 1 ต่อ 1; บรรทัดที่ไม่ติ๊กไม่มี Milestone เกิดขึ้น", prio="High"),
    dict(id="TC-D4-03", scenario="ยืนยัน SO แล้วออกใบแจ้งหนี้มัดจำแบบเปอร์เซ็นต์",
         pre="SO ยืนยันแล้ว ยังไม่เคยออกใบแจ้งหนี้ใดๆ",
         steps=["เปิด SO กดปุ่ม \"Create Invoice\"", "เลือกตัวเลือก \"Down payment (percentage)\"", "กรอกเปอร์เซ็นต์มัดจำ", "กด Create Draft Invoice"],
         sample="Down payment = 30%",
         expected="ได้ใบแจ้งหนี้มัดจำยอด 30% ของราคารวม SO สถานะ Draft", prio="High"),
    dict(id="TC-D4-04", scenario="ตรวจสมุดรายวันของใบแจ้งหนี้มัดจำหลัง Post",
         pre="ใบแจ้งหนี้มัดจำจาก TC-D4-03 ถูกยืนยัน (Post) แล้ว",
         steps=["เปิดใบแจ้งหนี้มัดจำที่ Post แล้ว", "ไปแท็บ Journal Items"],
         sample="-",
         expected="เครดิตเข้าบัญชีหนี้สิน (เงินมัดจำรับล่วงหน้า) ไม่ใช่บัญชีรายได้ขาย — งานยังไม่เสร็จ ยังรับรู้เป็นรายได้ไม่ได้", prio="High"),
  ]),
  dict(cat_id="D5", title="D5. คลังเช็คก้อนหินที่มีอยู่ — พร้อมต้นทุนจริงจากใบสั่งซื้อ",
       subtitle="stone_bundle.py — Cost/CBM = ราคาจริงจาก PO Line + ส่วนแบ่ง Landed Cost ของ Container · 4 test cases",
       cases=[
    dict(id="TC-D5-01", scenario="Block ที่ผูกกับ PO Line แล้ว ต้นทุนคำนวณจากราคาจริงใน PO",
         pre="Block ผูก Purchase Order Line ที่ยืนยันแล้ว (มีราคา/ปริมาตรจริง)",
         steps=["เปิดฟอร์ม Block ที่จะใช้ตัด", "ดูค่า Cost/CBM (หรือ Cost/Sq.Mt. ถ้าเป็นวัสดุที่ไม่มี Block Product)"],
         sample="PO Line ราคารวม 50,000 บาท, Block ปริมาตร 2.0 CBM",
         expected="Cost/CBM = 25,000 บาท (ราคารวม PO Line ÷ ปริมาตร Block) ตรงกับที่คำนวณเองเป๊ะ", prio="High"),
    dict(id="TC-D5-02", scenario="Block อยู่ใน Container ที่มีค่า Landed Cost (freight/duty) แล้ว",
         pre="Container ที่ Block นี้อยู่ ตั้งค่า Landed Cost Total ไว้แล้ว และมี Block อื่นร่วม Container เดียวกัน",
         steps=["เปิดฟอร์ม Block", "ดูค่า Landed Cost/CBM แยกจาก PO Cost/CBM", "ตรวจ Cost/CBM รวม (คอลัมน์หลัก)"],
         sample="Container Landed Cost Total = 10,000 บาท, Block นี้มีปริมาตรเป็นสัดส่วนหนึ่งของ CBM รวมทั้ง Container",
         expected="Landed Cost/CBM ถูกปันส่วนตามสัดส่วนปริมาตรของ Block นี้เทียบ Block อื่นใน Container เดียวกัน และ Cost/CBM รวม = PO Cost/CBM + Landed Cost/CBM", prio="Medium"),
    dict(id="TC-D5-03", scenario="Block ที่ยังไม่ได้ผูก PO Line เลย (กรอกมือ)",
         pre="Block สร้างขึ้นโดยไม่ผูก Purchase Order Line",
         steps=["เปิดฟอร์ม Block ที่ไม่มี PO Line ผูกอยู่", "ดูค่า Cost/CBM"],
         sample="-",
         expected="Cost/CBM ขึ้นเป็น 0 ไม่ error (ไม่มี PO อ้างอิงให้คำนวณ)", prio="Low"),
    dict(id="TC-D5-04", scenario="กด \"Create Cut Order\" จากฟอร์ม Block ที่มีต้นทุนจริงแล้ว",
         pre="Block มีต้นทุนจริงจาก PO ตาม TC-D5-01 และมี SO รอตัดอยู่",
         steps=["เปิดฟอร์ม Block", "กดปุ่ม \"Create Cut Order\"", "ระบุขนาดที่จะตัดตาม SO แล้วยืนยัน"],
         sample="-",
         expected="Cut Order สร้างสำเร็จ อ้างอิงต้นทุนจริงของ Block นี้ (ไม่ใช่ค่าประเมินตอน Setup) ในการคำนวณต้นทุนแผ่นที่ตัดได้", prio="Medium"),
  ]),
  dict(cat_id="D6", title="D6. ตัดหินตามขนาดที่ขาย — แผ่นผูกกับ SO + ต้นทุนติดป้าย Analytic ทันที",
       subtitle="regression ของหมวด A6/A7/B3 เดิม + multi-plan Analytic tagging (โค้ดเปลี่ยน 26 ส.ค. — เสี่ยง regression สูง) · 5 test cases",
       cases=[
    dict(id="TC-D6-01", scenario="ยืนยัน Cut Order — แผ่นที่ตัดได้ผูกกับ SO เดิมโดยอัตโนมัติ",
         note="regression ของ TC-B3 กลุ่ม Cut-to-Order",
         pre="Cut Order (MO) ผูกกับ Sale Order Line อยู่แล้ว (สร้างจาก TC-D5-04)",
         steps=["ระบุขนาดที่จะตัด (L × H)", "ยืนยัน Cut Order จนเสร็จ", "เปิดแผ่นที่ได้ดู Lot/Serial + ลิงก์กลับ SO"],
         sample="Slab L (M) = 2.0<br>Slab H (M) = 1.5",
         expected="แผ่นที่ตัดได้ถูก Hold ให้กับ Sale Order Line เดิมทันที พร้อม Lot/Serial เฉพาะแผ่น", prio="High"),
    dict(id="TC-D6-02", scenario="ต้นทุนวัสดุของแผ่นที่ตัดได้ ถูกติดป้าย Analytic ตาม distribution ของ SO Line",
         pre="SO Line ที่ผูก Cut Order นี้มี Analytic Distribution อยู่แล้ว (จาก D2/D3-02)",
         steps=["ยืนยัน Cut Order จนเสร็จ", "เปิดรายงาน Analytic Items กรองด้วยชื่อ Cut Order นี้"],
         sample="-",
         expected="พบรายการต้นทุนวัสดุของแผ่นนี้ ติดป้าย Analytic Account เดียวกับที่ SO Line ระบุไว้", prio="High"),
    dict(id="TC-D6-03", scenario="ต้นทุนแรงงานตัด ติดป้าย Analytic ทั้ง 2 มิติพร้อมกัน (โครงการ + ประเภทวัสดุ)",
         note="⚠️ โค้ดจุดนี้เปลี่ยน 2026-08-26 (รองรับหลาย Plan พร้อมกันในบรรทัดเดียว) — วันก่อนทำเอกสารนี้ ยังไม่เคยมี Test Case คุมจุดนี้มาก่อน เสี่ยง regression สูงสุดในหมวดนี้",
         pre="SO Line ที่ผูก Cut Order นี้มี Analytic Distribution ตั้งไว้ 2 Plan พร้อมกัน (\"โครงการ\" และ \"ประเภทวัสดุ\")",
         steps=["ยืนยัน Cut Order จนเสร็จ (มี Workorder บันทึกเวลาแล้ว)", "เปิดรายงาน Analytic Items กรองด้วยชื่อ Cut Order นี้ หารายการ \"Stone Cutting Labor\""],
         sample="-",
         expected="พบรายการต้นทุนแรงงานตัด 2 รายการ (หรือแสดงผลรวมทั้ง 2 Account) — ติดป้ายทั้ง Analytic Account ของโครงการ และของประเภทวัสดุ ครบทั้งคู่ ไม่ใช่แค่ตัวใดตัวหนึ่ง", prio="High"),
    dict(id="TC-D6-04", scenario="Cut Order แบบไม่มี SO ผูก (ตัดเข้าสต็อกล่วงหน้า) — เลือก Project (No SO)",
         note="ADR-032 regression",
         pre="Block ยังไม่มี SO ผูก แต่ต้องการตัดเข้าสต็อกไว้ล่วงหน้า",
         steps=["เปิด Cut Order Wizard แบบไม่มี SO", "เลือกช่อง \"Project (No SO)\" เป็น Analytic Account ที่ต้องการ", "ยืนยัน Cut Order จนเสร็จ", "เปิดรายงาน Analytic Items ดู"],
         sample="Project (No SO) = Analytic Account ของโครงการที่เลือกไว้",
         expected="ต้นทุนแรงงานตัดยังติดป้าย Analytic Account ที่เลือกไว้ 100% ไม่หายไปทั้งที่ไม่มี SO ผูก", prio="Medium"),
    dict(id="TC-D6-05", scenario="Cut Order ครั้งแรกของบริษัทที่ยังไม่เคยมี Workcenter \"Stone Cutting\"",
         note="regression เบา ของ TC-A6 กลุ่ม BOM auto-provisioning",
         pre="บริษัทนี้ยังไม่เคยมี mrp.workcenter ชื่อ \"Stone Cutting\" มาก่อน",
         steps=["สั่ง Cut Order ครั้งแรกของบริษัทนี้", "ตรวจ Manufacturing &gt; Work Centers"],
         sample="-",
         expected="ระบบสร้าง Workcenter \"Stone Cutting\" ให้อัตโนมัติ 1 ตัวต่อบริษัท ไม่ error แม้ยังไม่เคยตั้งมาก่อน", prio="Low"),
  ]),
  dict(cat_id="D7", title="D7. ค่าขนส่ง + ค่าใช้จ่ายที่ไม่ได้วางแผนไว้ล่วงหน้า",
       subtitle="Native Odoo Vendor Bill Analytic — เลือกมือครั้งเดียวตอนบันทึกบิล เห็นต้นทุนจริงทั้งหมด · 3 test cases",
       cases=[
    dict(id="TC-D7-01", scenario="บันทึกบิลผู้ขายค่าขนส่งหน้างาน ผูก Analytic โครงการ",
         pre="มี Project จาก D4 อยู่แล้ว (มี Analytic Account ของโครงการนั้นให้เลือก)",
         steps=["Accounting &gt; Vendors &gt; Bills &gt; New", "กรอกบรรทัดค่าขนส่ง", "เปิด Analytic Distribution ของบรรทัดนั้น เลือก Analytic Account ของโครงการ 100%", "Confirm"],
         sample="รายการ = \"ค่าขนส่งหน้างาน\", บัญชี = Freight &amp; Transportation, จำนวนเงิน = 2,200<br>Analytic = โครงการ S00042 100%",
         expected="บิลบันทึกสำเร็จ ผูก Analytic โครงการไว้ครบ", prio="High"),
    dict(id="TC-D7-02", scenario="บันทึกบิลค่าใช้จ่ายนอกแผนเดิม (ไม่ได้อยู่ในใบเสนอราคาตั้งแต่ต้น)",
         pre="เหมือน TC-D7-01",
         steps=["บันทึกบิลผู้ขายอีกใบ รายการที่ไม่เคยอยู่ในใบเสนอราคาเดิม", "ผูก Analytic โครงการเดียวกัน", "Confirm"],
         sample="รายการ = \"วัสดุยึด/กาวเสริม (นอกแผนเดิม)\", บัญชี = General subcontracting, จำนวนเงิน = 850<br>Analytic = โครงการ S00042 100%",
         expected="บิลบันทึกสำเร็จเช่นกัน แม้ไม่เคยอยู่ในใบเสนอราคาเดิมเลย — ยังติดป้ายโครงการเดียวกันได้ทันที", prio="Medium"),
    dict(id="TC-D7-03", scenario="บิลค่าใช้จ่ายที่ลืมผูก Analytic (ไม่เลือกเลย)",
         note="หมายเหตุ: จุดเสี่ยงที่ทำให้ต้นทุนจริงในรายงานกำไรดูต่ำกว่าความจริง — ดู TC-D9-04",
         pre="-",
         steps=["บันทึกบิลผู้ขายรายการหนึ่ง ไม่เลือก Analytic Distribution เลย", "Confirm"],
         sample="-",
         expected="บิลบันทึกได้ปกติ (ไม่ใช่ฟิลด์บังคับ) แต่รายการนี้จะไม่ปรากฏในรายงานกำไรของโครงการใดเลย", prio="Low"),
  ]),
  dict(cat_id="D8", title="D8. ติดตั้งหน้างานเสร็จ → ปิดยอด → รับรู้รายได้",
       subtitle="Milestone auto-reach (custom) + WHT (custom) + Down Payment reversal (Native) · 6 test cases",
       cases=[
    dict(id="TC-D8-01", scenario="ปิด Task \"ติดตั้งหน้างาน\" เป็นเสร็จสมบูรณ์ → Milestone ขึ้นสถานะเองอัตโนมัติ",
         note="boq_estimation/project_task.py write() override — ทำงานเฉพาะเมื่อ Milestone นั้นผูกกับ Task เดียว (len==1) เท่านั้น",
         pre="Task \"ติดตั้งหน้างาน\" ผูก Milestone อยู่ 1:1 (ไม่มี Task อื่นผูก Milestone เดียวกัน) ยังไม่ Reached",
         steps=["เปิด Task \"ติดตั้งหน้างาน\"", "เปลี่ยนสถานะ (หรือลาก Kanban ไปคอลัมน์ Done) เป็นเสร็จสมบูรณ์", "เปิด Project ดู Milestones"],
         sample="-",
         expected="Milestone ที่ผูกกับ Task นี้ขึ้นสถานะ Reached ให้อัตโนมัติ ไม่ต้องติ๊กแยก", prio="High"),
    dict(id="TC-D8-02", scenario="Milestone ที่ผูกกับหลาย Task พร้อมกัน — ปิด Task เดียวไม่พอให้ Reached",
         note="edge case ของ TC-D8-01 — กันเข้าใจผิดว่าปิด Task ใดก็ได้ Milestone Reached",
         pre="Milestone เดียวผูกกับ Task มากกว่า 1 ใบ (กรณีพิเศษ ไม่ใช่ 1:1 ปกติ)",
         steps=["ปิด Task ใบแรกที่ผูก Milestone นี้เป็นเสร็จสมบูรณ์ (ยังเหลืออีกใบไม่เสร็จ)", "เปิด Project ดู Milestones"],
         sample="-",
         expected="Milestone ยังไม่ขึ้น Reached (เพราะเงื่อนไข auto-reach นับเฉพาะกรณี Milestone ผูก Task เดียวเท่านั้น)", prio="Low"),
    dict(id="TC-D8-03", scenario="บันทึกบิลค่าแรงติดตั้งพร้อม VAT 7% และหัก ณ ที่จ่าย 3%",
         pre="มี Vendor (ทีมติดตั้ง/subcontractor) ตั้งไว้แล้ว",
         steps=["Accounting &gt; Vendors &gt; Bills &gt; New", "กรอกบรรทัดค่าแรงติดตั้ง ตั้งภาษีขาย VAT 7%", "เพิ่มภาษีหัก ณ ที่จ่าย 3% (รายการภาษีที่ลงท้ายด้วย S = ค่าบริการ)", "ผูก Analytic โครงการ", "Confirm"],
         sample="รายการ = \"ค่าแรงติดตั้งหน้างาน\", ราคา = 5,000, VAT = 7%, ภาษีหัก ณ ที่จ่าย = \"3% WH C S\"",
         expected="บิล Post สำเร็จ ยอดสุทธิที่ต้องจ่ายผู้ขาย = ราคา + VAT − ยอดหัก ณ ที่จ่าย 3%", prio="High"),
    dict(id="TC-D8-04", scenario="พิมพ์ใบรับรองหัก ณ ที่จ่าย (Form 50-ทวิ) จากบิลที่ Post แล้ว",
         pre="บิลจาก TC-D8-03 Post แล้ว",
         steps=["เปิดบิลนั้น สังเกตปุ่ม \"Print WHT Certificate\" บนหัวฟอร์ม (ปรากฏเฉพาะบิลที่ Post แล้วและมีหัก ณ ที่จ่าย)", "กดปุ่มนั้น"],
         sample="-",
         expected="ได้ PDF ใบรับรองหัก ณ ที่จ่าย มีเลขที่ใบรับรองออกให้อัตโนมัติ พร้อมยอดฐานภาษี/อัตรา 3%/ยอดหัก ตรงกับบิล", prio="High"),
    dict(id="TC-D8-05", scenario="ออกใบแจ้งหนี้ปิดโครงการยอดเต็ม หลังเคยวางมัดจำแล้ว",
         pre="SO เคยออกใบแจ้งหนี้มัดจำ 30% ไปแล้ว (TC-D4-03/04) งานเสร็จสมบูรณ์แล้ว",
         steps=["เปิด SO กดปุ่ม \"Create Invoice\"", "เลือก \"Regular Invoice\" (ยอดที่เหลือทั้งหมด)", "Post ใบแจ้งหนี้"],
         sample="-",
         expected="ใบแจ้งหนี้หักลบมัดจำที่เคยวางไว้ออกจากยอดที่ต้องเรียกเก็บให้อัตโนมัติ", prio="High"),
    dict(id="TC-D8-06", scenario="ตรวจสมุดรายวันของใบแจ้งหนี้ปิดโครงการ",
         pre="ใบแจ้งหนี้จาก TC-D8-05 Post แล้ว",
         steps=["เปิดใบแจ้งหนี้ปิดโครงการ", "ไปแท็บ Journal Items"],
         sample="ตัวอย่างจากเดโม: เงินมัดจำรับล่วงหน้า 12,365.00 (Dr) / Sales Revenue 14,270.00 (Cr) / Trade Receivables 2,163.09 (Dr) / Output VAT 258.09 (Cr)",
         expected="บัญชีเงินมัดจำรับล่วงหน้าถูกล้างเต็มยอดที่เคยตั้งไว้ (Dr), บัญชีรายได้ขายได้รับยอดเต็มราคาขาย (Cr), มี Trade Receivables + Output VAT ของส่วนที่เหลือ", prio="High"),
  ]),
  dict(cat_id="D9", title="D9. Chart of Analytic Accounts — กำไร 2 มุมมอง + Gross Margin เจาะรายละเอียด",
       subtitle="Native Odoo Analytic Accounting Report — ต่อโครงการ vs ข้ามโครงการตามวัสดุ · 4 test cases",
       cases=[
    dict(id="TC-D9-01", scenario="เปิด Chart of Analytic Accounts ดูกำไรต่อโครงการ",
         pre="โครงการมีทั้งรายได้ (มัดจำ+ใบแจ้งหนี้ปิดงาน) และต้นทุนจริงครบทุกตัวผูก Analytic โครงการไว้แล้ว (D3-D8 ทำครบ)",
         steps=["Accounting &gt; Reporting &gt; Analytic Accounting &gt; Chart of Analytic Accounts", "หา Analytic Account ของโครงการ (เช่น S00042)"],
         sample="-",
         expected="เห็นยอดกำไร/ขาดทุนสุทธิของโครงการนั้น เทียบรายได้เต็มกับต้นทุนจริงทั้งหมดที่เคยผูกไว้ครบทุกจุดตลอด flow", prio="High"),
    dict(id="TC-D9-02", scenario="ดูกำไรข้ามโครงการ ตามประเภทวัสดุ (มุมมองที่ 2)",
         pre="มีหลายโครงการที่เคยขายวัสดุประเภทเดียวกัน (เช่น Marble) ผูก Analytic Plan \"ประเภทวัสดุ\" ไว้แล้ว",
         steps=["เปิด Chart of Analytic Accounts", "กรอง/จัดกลุ่มด้วย Analytic Plan \"ประเภทวัสดุ\"", "หา Account \"Marble\""],
         sample="-",
         expected="เห็นยอดกำไรรวมของ \"Marble\" ข้ามทุกโครงการที่เคยขายวัสดุนี้ ได้จากหน้าเดียว ไม่ต้องเปิดทีละโครงการ", prio="High"),
    dict(id="TC-D9-03", scenario="กดปุ่ม \"Gross Margin\" บน Analytic Account ของโครงการ",
         pre="เหมือน TC-D9-01",
         steps=["เปิด Analytic Account ของโครงการ (S00042)", "กดสมาร์ทปุ่ม/ปุ่ม \"Gross Margin\""],
         sample="-",
         expected="เห็นรายการละเอียดทุกบรรทัดที่ประกอบเป็นกำไร ทั้งฝั่งรายได้ (มัดจำ, ใบแจ้งหนี้ปิดงาน) และต้นทุนจริงทุกตัว (วัสดุ, ค่าแรงตัด, ค่าแรงติดตั้ง, ขนส่ง, ค่าใช้จ่ายนอกแผน, ภาษีหัก ณ ที่จ่าย) ไม่ใช่แค่ยอดรวมก้อนเดียว", prio="High"),
    dict(id="TC-D9-04", scenario="รายการที่ไม่ได้ผูก Analytic (จาก TC-D7-03) จะไม่ขึ้นใน Gross Margin",
         note="หมายเหตุ: ยืนยันผลกระทบของ TC-D7-03 — ต้นทุนจริงจะดูต่ำกว่าความจริงถ้าลืมผูก Analytic ตอนบันทึกบิล",
         pre="มีบิลที่ไม่ได้ผูก Analytic ไว้ตาม TC-D7-03",
         steps=["เปิด Gross Margin ของโครงการที่เกี่ยวข้อง", "ตรวจว่ารายการนั้นปรากฏอยู่หรือไม่"],
         sample="-",
         expected="รายการที่ไม่ได้ผูก Analytic จะไม่ปรากฏในรายงาน Gross Margin ของโครงการเลย", prio="Medium"),
  ]),
]
