# Single source of truth for EMG-O Golden Path test cases — "Slab" (ชุดที่ 2 จาก 3:
# Block -> Slab -> FG), rebuilt after ADR-087 "Slab = Lot" (รอบ Slab-Lot, 2026-10-04/05).
#
# This is story 2. Story 1 (Block) left two Blocks in stock; this story cuts one of them
# into Slabs, buys a few finished Slabs from a supplier, and sells Slabs to a customer.
# FG (Countertop / เจดีย์บัว) is story 3 and starts only when the user says so.
#
# Golden Path discipline (see feedback_golden_path_test_case memory): happy path only,
# no field-validation/error cases, every step phrased for a non-technical user.
# Cut by the user's earlier call (same as the Block story): returns/refund cases and
# cross-company are not part of this story.
#
# Data provenance: fresh live run, 2026-10-05, driven through the real Odoo web UI
# (Playwright, headless Chromium) on `eg-tst` (https://eg-tst.mx-erp.com, company
# Empire Granite, user admin), code v2.106 on branch test/emg-erp-ee (merged with
# redesign/slab-lot). Fixtures this run created / left in place:
#   Cut Order EG01/STCUT/00021 on BLK-26-0006 -> 80 Slab lots BLK-26-0006-1 .. -80
#   (4 sold on S00174, then all 4 returned on EG01/IN/00058 and inspected -> all 80 Available); PO P00055 + receipt EG01/IN/00057 ->
#   SLB-26-0001..0004 (Available); SO S00174, delivery EG01/OUT/00058, invoice INV/2026/00003.
#   Block BLK-26-0007 (5.04 m3) is still uncut, left for the FG story.
#
# Column model per case: id, scenario, note (optional amber callout), pre, steps (list),
# sample ('-' if nothing to key), expected, prio, shot (screenshot path, clickable).

SHOT = "assets/golden-path-slab/"

CATEGORIES = [
  dict(cat_id="S1", title="S1. ตัด Block เป็น Slab (Cut Order)",
       subtitle="เปิดใบตัด → ย้าย Block ไปสถานีตัด → Confirm → ตัดเสร็จได้ Slab รายแผ่น · 5 test cases",
       cases=[
    dict(id="TC-GP-SLB-01", scenario="สร้างใบตัด (Cut Order) แล้วเลือก Block ที่จะตัด",
         pre="มี Block ในคลัง (จากชุด Block เช่น BLK-26-0006 ซึ่งมี 6.00 m³)",
         steps=["เปิดแอป Manufacturing &gt; Operations &gt; Manufacturing Orders &gt; New",
                "ที่ \"Stone Block\" เลือก Block ที่จะตัด"],
         sample="Stone Block = BLK-26-0006",
         expected="ระบบเติมขนาดแผ่นที่จะตัดให้เอง (กว้าง 3.00 × สูง 1.25 ม. หนา 2 ซม.) และคำนวณจำนวนแผ่นที่คาดว่าจะได้ไว้ในแท็บ \"Planned/Actual Slabs\" = 80 แถว (แถวละ 1 แผ่น, 3.00 × 1.25 × 0.02 ม.) — Block 6.00 m³ ตัดได้ 80 แผ่นพอดี",
         prio="High", shot=SHOT + "gp-slab-01-cut-order-block.png"),
    dict(id="TC-GP-SLB-02", scenario="ย้าย Block ไปสถานีตัด (ย้ายด่วน)",
         note="แถบเตือนสีส้มบนหน้าใบตัดจะเปลี่ยนเป็น \"พร้อม Confirm แล้ว\" เมื่อเปิดหน้านี้ใหม่ (รีเฟรช) — เป็นแค่ข้อความ ไม่กระทบการทำงาน",
         pre="ทำ TC-GP-SLB-01 เสร็จแล้ว และกด Save แล้ว",
         steps=["บนใบตัด กดปุ่ม \"ย้ายด่วน (Move to Production)\""],
         sample="-",
         expected="ระบบแจ้งเตือนสีเขียวว่า \"ย้ายสำเร็จ Block BLK-26-0006 ย้ายไป Stone Production แล้ว 6.000 หน่วย — กด Confirm ได้เลย\" (Block ถูกย้ายจาก Stone Available ไปสถานีตัดแล้ว)",
         prio="High", shot=SHOT + "gp-slab-02-move-to-production.png"),
    dict(id="TC-GP-SLB-03", scenario="เลือกเหตุผลของใบตัด แล้วกด Confirm",
         note="ใบตัดที่ไม่ได้ผูกกับใบสั่งขาย ต้องเลือก \"Reason (No SO)\" ก่อนเสมอ ถ้าไม่เลือก ระบบจะไม่ให้ Confirm — กรณีตัดเข้าสต็อกทั่วไปให้เลือก \"อื่นๆ (Other)\"",
         pre="ทำ TC-GP-SLB-02 เสร็จแล้ว",
         steps=["ที่ขั้นตอนที่ 3 ช่อง \"Reason (No SO)\" เลือกเหตุผล",
                "กด Save",
                "กด Confirm"],
         sample="Reason (No SO) = อื่นๆ (Other)",
         expected="ใบตัดเปลี่ยนสถานะเป็น In Progress (ใบตัดตัวอย่างจริง EG01/STCUT/00021) — ปุ่ม Complete Cut พร้อมใช้งาน",
         prio="High", shot=SHOT + "gp-slab-03-confirm-reason.png"),
    dict(id="TC-GP-SLB-04", scenario="ตัดเสร็จ กด Complete Cut ได้ Slab ทุกแผ่น",
         note="ต้นทุน Block ถูกแบ่งให้ทุกแผ่นเท่ากัน: Block 6.00 m³ ต้นทุน 97,200 บาท ÷ 80 แผ่น = 1,215 บาทต่อแผ่น (ตรวจจากต้นทุนขายตอนขายใน TC-GP-SLB-13) — ถ้าหน้างานตัดได้ขนาดจริงต่างจากแผน ให้แก้คอลัมน์ Actual L/H/Thickness ในแท็บ Planned/Actual Slabs ก่อนกดปุ่ม",
         pre="ทำ TC-GP-SLB-03 เสร็จแล้ว",
         steps=["(ถ้าตัดจริงได้ขนาดต่างจากแผน แก้ Actual L / H / Thickness ในแท็บ Planned/Actual Slabs)",
                "กดปุ่ม \"Complete Cut\""],
         sample="-",
         expected="ระบบแจ้งเตือนสีเขียว \"Complete Cut สำเร็จ EG01/STCUT/00021 ตัดได้ 80 แผ่นจาก BLK-26-0006\" · ใบตัดขึ้น Done · Quantity 80.00 · ปุ่ม Serial Numbers แสดง 80",
         prio="High", shot=SHOT + "gp-slab-04-complete-cut.png"),
    dict(id="TC-GP-SLB-05", scenario="ตรวจ Slab ที่ตัดได้ในรายการ Slab",
         note="ภาพตัวอย่างถ่ายหลังขาย 4 แผ่นไปแล้ว (TC-GP-SLB-10 ถึง 13) จึงแสดง 76 แผ่นที่ยัง Available — ตอนตัดเสร็จใหม่ๆ จะเห็น 80 แผ่น",
         pre="ทำ TC-GP-SLB-04 เสร็จแล้ว",
         steps=["เปิดแอป Stone Slab &gt; Slabs &gt; All Slabs",
                "ที่ช่องค้นหาพิมพ์ชื่อ Block แล้วกด Enter"],
         sample="ค้นหา = BLK-26-0006",
         expected="เห็น Slab ชื่อ BLK-26-0006-1, -2, -3 … ต่อเนื่องไปถึง -80 แผ่นละบรรทัด ขนาด 3.00 × 1.25 × 0.020 ม. = 3.75 ตร.ม. (รวม 300 ตร.ม.) สถานะ Available คอลัมน์ Block ชี้กลับไปที่ BLK-26-0006",
         prio="High", shot=SHOT + "gp-slab-05-slab-list.png"),
  ]),
  dict(cat_id="S2", title="S2. รับ Slab สำเร็จรูปจากผู้ขาย (Purchase)",
       subtitle="ซื้อแผ่นสำเร็จรูปเป็นราคาต่อตร.ม. — ระบบคิดมูลค่าจากขนาดจริงของแต่ละแผ่น · 3 test cases",
       cases=[
    dict(id="TC-GP-SLB-06", scenario="สร้างใบสั่งซื้อ (PO) Slab สำเร็จรูป ราคาต่อตารางเมตร แล้ว Confirm",
         note="ช่อง \"Qty (Sq.M)\" ระบบคำนวณให้จากขนาดมาตรฐานของสินค้า (4 แผ่น × 4.80 = 19.20 ตร.ม.) เป็นแค่ปริมาณโดยประมาณ — มูลค่าจริงจะคิดจากขนาดที่วัดได้ตอนรับของ (TC-GP-SLB-07)",
         pre="มีหินชนิดนี้ในระบบ (GP Block Marble จากชุด Block) · มีผู้ขายในระบบ",
         steps=["เปิดแอป Purchase &gt; New เลือก Vendor",
                "กด \"Add a product\" เลือก \"GP Block Marble - Slab\"",
                "ช่อง Quantity ใส่จำนวนแผ่น",
                "ช่อง Price / Sq.M ใส่ราคาต่อตารางเมตร",
                "กด Confirm Order"],
         sample="Vendor = Demo Stone Supplier<br>Quantity = 4 แผ่น<br>Price / Sq.M = 1,300",
         expected="PO ขึ้นสถานะ Purchase Order: Qty (Sq.M) 19.20, Quantity 4.00 · ยอดก่อน VAT 24,960.00 บาท, VAT 1,747.20, รวม 26,707.20 (ตัวอย่างจริง P00055) มีสมาร์ทปุ่ม Receipt 1 ใบ",
         prio="High", shot=SHOT + "gp-slab-06-po-slab.png"),
    dict(id="TC-GP-SLB-07", scenario="รับของ กรอกขนาดจริงของแต่ละแผ่น แล้ว Validate",
         pre="ทำ TC-GP-SLB-06 เสร็จแล้ว",
         steps=["ที่ PO กดปุ่ม Receive เปิดใบรับของ",
                "ที่แถวสินค้า กด \"Details\" จะเห็น 4 แถว (แถวละ 1 แผ่น)",
                "แต่ละแถวกรอก กว้าง / ยาว / หนา ของแผ่นที่วัดได้จริง (ช่อง Lot/Serial เว้นว่างได้ ระบบตั้งชื่อให้เอง)",
                "กด Save แล้วกด Validate"],
         sample="แผ่น 1: กว้าง 1.58 × ยาว 2.95<br>แผ่น 2: กว้าง 1.60 × ยาว 3.00<br>แผ่น 3: กว้าง 1.55 × ยาว 2.90<br>แผ่น 4: กว้าง 1.60 × ยาว 3.00<br>หนาทุกแผ่น = 0.02 ม.",
         expected="ใบรับของขึ้น Done (EG01/IN/00057) แยกเป็น 4 บรรทัดบรรทัดละ 1 แผ่น · ระบบตั้งชื่อ Lot ให้เอง SLB-26-0001 ถึง SLB-26-0004 · มูลค่าสต็อกรวม 24,382.80 บาท (= พื้นที่จริง 18.756 ตร.ม. × 1,300 — แผ่นละ 6,059.30 / 6,240.00 / 5,843.50 / 6,240.00)",
         prio="High", shot=SHOT + "gp-slab-07-receipt-sizes.png"),
    dict(id="TC-GP-SLB-08", scenario="ตรวจ Slab ที่รับเข้ามาในรายการ Slab",
         pre="ทำ TC-GP-SLB-07 เสร็จแล้ว",
         steps=["เปิดแอป Stone Slab &gt; Slabs &gt; All Slabs",
                "ที่ช่องค้นหาพิมพ์ SLB-26 แล้วกด Enter"],
         sample="ค้นหา = SLB-26",
         expected="เห็น 4 แผ่น ขนาดและพื้นที่ตรงกับที่วัด: 1.58 × 2.95 = 4.66 · 1.60 × 3.00 = 4.80 · 1.55 × 2.90 = 4.50 · 1.60 × 3.00 = 4.80 ตร.ม. สถานะ Available (คอลัมน์ Block ว่าง เพราะซื้อมาเป็นแผ่นสำเร็จ ไม่ได้ตัดจาก Block ของเรา)",
         prio="Medium", shot=SHOT + "gp-slab-08-received-slabs.png"),
  ]),
  dict(cat_id="S3", title="S3. ขาย Slab (Sales)",
       subtitle="ขายเป็นรายแผ่น เลือก Slab ที่ต้องการ → ส่งของโดยสแกน Serial → ออกใบแจ้งหนี้ · 5 test cases",
       cases=[
    dict(id="TC-GP-SLB-09", scenario="สร้างใบเสนอราคา (SO) และเลือกสินค้า Slab",
         pre="มี Slab พร้อมขายใน Stone Available · มีลูกค้าในระบบ",
         steps=["เปิดแอป Sales &gt; New เลือกลูกค้า",
                "กด \"Add a product\" เลือก \"GP Block Marble - Slab\"",
                "ในหน้าต่าง Configure your product เลือก Finish และ Thickness แล้วกด Confirm",
                "กด Save"],
         sample="ลูกค้า = Demo Hotel Customer<br>Finish = Polished · Thickness = 2 cm",
         expected="ได้บรรทัดสินค้า \"GP Block Marble - Slab (Polished, 2 cm)\" ราคา 4,500 บาท/ตร.ม. (ตอนนี้ยังเป็นขนาดมาตรฐาน 3.00 × 1.60 = 4.80 ตร.ม. → 21,600 บาท — ยอดจริงจะคำนวณใหม่เมื่อเลือกแผ่นในขั้นถัดไป) · บันทึกแล้วได้เลขที่ใบ S00174",
         prio="High", shot=SHOT + "gp-slab-09-so-configurator.png"),
    dict(id="TC-GP-SLB-10", scenario="เลือก Slab ที่จะขาย (หน้าต่างเลือก Slab / Lot)",
         pre="ทำ TC-GP-SLB-09 เสร็จแล้ว (บรรทัดสินค้าถูกบันทึกแล้ว)",
         steps=["ที่บรรทัดสินค้า กดปุ่มไอคอนรายการ \"เลือก Slab / Select Slabs\" ท้ายบรรทัด",
                "ในหน้าต่าง กด \"Add a line\" แล้วเลือก Slab ทีละแผ่น (พิมพ์ชื่อแล้วเลือก) — ทำซ้ำจนครบ",
                "กด \"ยืนยันการเลือก\""],
         sample="เลือก 4 แผ่น: BLK-26-0006-1, -2, -3, -4",
         expected="หน้าต่างแสดงขนาด จำนวนที่ว่าง และตร.ม. ของแต่ละแผ่น พื้นที่ที่เลือกรวม 15.00 ตร.ม. · พอกดยืนยัน บรรทัดสินค้าเปลี่ยนเป็น \"4 แผ่น = 15.00 ตร.ม. · 4,500 ฿/ตร.ม.\" พร้อมรายชื่อแผ่นที่เลือก · ยอดก่อน VAT 67,500.00 บาท, VAT 4,725.00, รวม 72,225.00",
         prio="High", shot=SHOT + "gp-slab-10-select-slabs.png"),
    dict(id="TC-GP-SLB-11", scenario="กด Confirm ใบสั่งขาย",
         note="แถบสีแดง \"ขนาดแผ่นจริงต่างจากที่เสนอลูกค้า\" ขึ้นเพราะใบเสนอราคาใช้ขนาดมาตรฐาน 3.00 × 1.60 (4.80 ตร.ม./แผ่น) แต่แผ่นจริงที่เลือกคือ 3.75 ตร.ม./แผ่น — ระบบล็อกยอดไว้ที่ 67,500 และเตือนเซลล์ให้แจ้งลูกค้า เป็นพฤติกรรมตามออกแบบ (ล็อกยอด ADR-079) ไม่ใช่ข้อผิดพลาด",
         pre="ทำ TC-GP-SLB-10 เสร็จแล้ว",
         steps=["กดปุ่ม Confirm บนใบสั่งขาย"],
         sample="-",
         expected="สถานะเป็น Sales Order · ยอดคงเดิม 67,500.00 + VAT 4,725.00 = 72,225.00 · มีสมาร์ทปุ่ม Delivery 1 ใบ และ Slabs 4 แผ่น · คอลัมน์ Delivered ยังเป็น 0.00 จาก 4.00",
         prio="High", shot=SHOT + "gp-slab-11-so-confirmed.png"),
    dict(id="TC-GP-SLB-12", scenario="ส่งของ: สแกน Serial ทุกแผ่นก่อน Validate",
         note="ใบส่งของ Slab บังคับให้สแกน (หรือพิมพ์) ชื่อ Serial ของทุกแผ่นให้ตรงกับที่จะส่งก่อน Validate เพื่อกันส่งผิดแผ่น — ถ้ายังไม่สแกน ระบบจะแจ้งว่า \"สแกน Serial ไม่ตรง กรุณาสแกนให้ครบก่อน Validate\" พร้อมรายชื่อแผ่นที่ขาด (เจอจริงในรอบทดสอบนี้)",
         pre="ทำ TC-GP-SLB-11 เสร็จแล้ว",
         steps=["ที่ SO กดสมาร์ทปุ่ม Delivery",
                "ที่แถวสินค้ากด \"Details\"",
                "ที่คอลัมน์ \"Scanned Serial\" ของแต่ละแถว สแกนหรือพิมพ์ชื่อ Serial ให้ตรงกับแผ่นในแถวนั้น",
                "กด Save แล้วกด Validate"],
         sample="แถว 1 → BLK-26-0006-1<br>แถว 2 → BLK-26-0006-2<br>แถว 3 → BLK-26-0006-3<br>แถว 4 → BLK-26-0006-4",
         expected="ใบส่งของขึ้น Done ปริมาณ 4.00 (ตัวอย่างจริง EG01/OUT/00058) ตัดสต็อกจาก Stone Available — Slab ทั้ง 4 แผ่นไม่อยู่ในรายการ Available อีกต่อไป (เหลือ 76 แผ่นของ BLK-26-0006)",
         prio="High", shot=SHOT + "gp-slab-12-delivery-scanned.png"),
    dict(id="TC-GP-SLB-13", scenario="ออกใบแจ้งหนี้ และตรวจรายการบัญชี (รายได้ + ต้นทุนขาย)",
         pre="ทำ TC-GP-SLB-12 เสร็จแล้ว",
         steps=["ที่ SO กด Create Invoice &gt; เลือก Regular invoice &gt; Create Draft",
                "ที่ใบแจ้งหนี้ กด Confirm",
                "เปิดแท็บ Journal Items"],
         sample="-",
         expected="ใบแจ้งหนี้ขึ้น Posted (INV/2026/00003) · รายการบัญชีสมดุลที่ 77,085.00: รายได้ 411100 = 67,500.00 · VAT ขาย 213200 = 4,725.00 · ลูกหนี้ 112100 = 72,225.00 · ต้นทุนขาย 511110 = 4,860.00 และตัดสต็อกออกจากบัญชี 113120 = 4,860.00 (= 4 แผ่น × 1,215 ตรงกับต้นทุนต่อแผ่นจาก TC-GP-SLB-04)",
         prio="High", shot=SHOT + "gp-slab-13-invoice-journal.png"),
  ]),
  dict(cat_id="S4", title="S4. ลูกค้าคืน Slab (Return)",
       subtitle="ลูกค้าส่งแผ่นคืน → รับเข้าที่ \"รอตรวจ\" → ตรวจแล้วนำกลับไปขายได้อีก · 5 test cases",
       cases=[
    dict(id="TC-GP-SLB-14", scenario="เปิดใบคืนจากใบส่งของ (Return)",
         note="หน้าต่าง Return ขึ้นจำนวนเป็น 0.00 ตามที่ออกแบบ — ให้กด \"Return All\" (คืนทั้งหมด) หรือแก้จำนวนเอง ปลายทางของใบคืนถูกตั้งเป็น \"Returned - Inspect\" ให้อัตโนมัติ เพราะแผ่นที่ลูกค้าคืนต้องตรวจก่อนเสมอ",
         pre="ทำ TC-GP-SLB-12 เสร็จแล้ว (ใบส่งของ EG01/OUT/00058 สถานะ Done)",
         steps=["เปิดใบส่งของที่สถานะ Done (จาก SO กดสมาร์ทปุ่ม Delivery)",
                "กดปุ่ม \"Return\" ด้านบน",
                "ในหน้าต่าง Return กดปุ่ม \"Return All\""],
         sample="คืนทั้ง 4 แผ่นของใบส่งของ EG01/OUT/00058",
         expected="ระบบสร้างใบรับคืนใหม่ทันที (ตัวอย่างจริง EG01/IN/00058) สถานะ Ready · รับจาก Demo Hotel Customer · ปลายทาง Stone Inventory/Returned - Inspect · อ้างอิง \"Return of EG01/OUT/00058\" · Demand 4.00",
         prio="High", shot=SHOT + "gp-slab-14-return-wizard.png"),
    dict(id="TC-GP-SLB-15", scenario="ระบุแผ่นที่ลูกค้าส่งคืนจริง (Details)",
         note="ใบรับคืนของ Slab เริ่มต้นโดยไม่เลือกแผ่นไว้ให้ ผู้รับของต้องระบุเองว่าแผ่นไหนกลับมา (ดีกว่าให้ระบบเดา เพราะลูกค้าอาจคืนไม่ครบ) ช่อง Lot/Serial จะแสดงเฉพาะแผ่นที่ถูกส่งไปที่ลูกค้าเท่านั้น",
         pre="ทำ TC-GP-SLB-14 เสร็จแล้ว",
         steps=["ที่แถวสินค้าของใบรับคืน กด \"Details\"",
                "กด \"Add a line\" แล้วพิมพ์ชื่อ Slab เลือกจากรายการ ใส่จำนวน 1 — ทำซ้ำทีละแผ่น",
                "กด Save"],
         sample="BLK-26-0006-1, -2, -3, -4 (แผ่นละ 1)",
         expected="ตาราง Detailed Operations แสดง 4 แถว ปลายทาง Store To ทุกแถวเป็น Stone Inventory/Returned - Inspect · รวม 4.00 Units ตรงกับ Demand",
         prio="High", shot=SHOT + "gp-slab-15-return-details.png"),
    dict(id="TC-GP-SLB-16", scenario="กด Validate รับของคืน",
         pre="ทำ TC-GP-SLB-15 เสร็จแล้ว",
         steps=["กดปุ่ม Validate บนใบรับคืน"],
         sample="-",
         expected="ใบรับคืนขึ้น Done · Quantity 4.00 จาก Demand 4.00 · Effective Date เป็นเวลาที่กด · แชตด้านขวาบันทึก Ready → Done",
         prio="High", shot=SHOT + "gp-slab-16-return-done.png"),
    dict(id="TC-GP-SLB-17", scenario="ตรวจว่า Slab ที่คืนอยู่ในสถานะ \"รอตรวจ\"",
         pre="ทำ TC-GP-SLB-16 เสร็จแล้ว",
         steps=["เปิดแอป Stone Slab &gt; Slabs &gt; All Slabs",
                "ลบตัวกรอง \"Available\" ออก แล้วค้นหาชื่อ Slab ที่คืน",
                "เปิดแผ่นที่คืน ดูช่อง Location และ Status"],
         sample="BLK-26-0006-1",
         expected="แผ่นที่คืนขึ้นสถานะ \"Returned - Pending Inspection\" (สีส้ม) อยู่ที่ Stone Inventory/Returned - Inspect · ยังไม่ถูกนับเป็นของพร้อมขาย (ไม่โผล่ในตัวกรอง Available) · แผ่นอื่นของ Block เดียวกันยังเป็น Available ตามเดิม",
         prio="High", shot=SHOT + "gp-slab-17-returned-pending.png"),
    dict(id="TC-GP-SLB-18", scenario="ตรวจแผ่นแล้ว นำกลับไปขายได้อีก",
         note="ถ้าตรวจแล้วแผ่นชำรุด ให้กดปุ่ม \"ชำรุด — ตัดทิ้ง (Scrap)\" แทน (ไม่ได้ทดสอบในชุดนี้ เพราะเป็นเส้นทางนอก Happy Path) การรับคืนในชุดนี้ยังไม่รวมการออกใบลดหนี้ (Credit Note) ให้ลูกค้า",
         pre="ทำ TC-GP-SLB-17 เสร็จแล้ว",
         steps=["เปิดหน้าของ Slab ที่คืน (ที่สถานะ Returned - Pending Inspection)",
                "กดปุ่ม \"ตรวจแล้ว — นำกลับไปขาย\" ด้านบนซ้าย",
                "ทำซ้ำกับแผ่นที่เหลือ"],
         sample="BLK-26-0006-1, -2, -3, -4",
         expected="สถานะเปลี่ยนเป็น Available · Location กลับเป็น Stone Inventory/Stone Available · ปุ่มตรวจแล้ว/ชำรุดหายไป · ต้นทุนยังเป็น 1,215.00 บาทเท่าเดิม · Slab กลับมาเลือกขายได้ใหม่ (BLK-26-0006 กลับเป็น 80 แผ่น Available)",
         prio="High", shot=SHOT + "gp-slab-18-inspect-ok.png"),
  ]),
]
